melt-ui/melt-ui

src/lib/builders/accordion/index.ts, src/lib/builders/checkbox/index.ts, src/lib/builders/radio-group/index.ts, src/lib/builders/select/index.ts, src/lib/builders/tabs/index.ts, src/lib/builders/toggle-group/index.ts, src/lib/internal/helpers/index.ts, src/lib/internal/helpers/keyboard.ts
I added a `kbd` object which maps commonly used keyboard keys to their corresponding string values.
This prevents us from hard-coding strings all over the place & also guarantees typesafety/accuracy considering `KeyboardEvent.key` is just typed as a `string`.
=> add keyboard constant object

README.md
This PR fixes a strange issue in the install section of the readme.md, where "npm i" was present in all package managers commands.
=> Fix install instructions for @melt-ui/svelte in readme.md

.changeset/forty-hounds-beg.md, package.json, src/lib/internal/helpers/is.ts
This PR adjusts isBrowser detection to not rely on the window variable, which can be declared in various environments, such as e.g. Deno. 
Prior art: https://github.com/TanStack/virtual/pull/516 https://github.com/framer/motion/pull/1522 https://remix.run/docs/en/1.16.1/pages/gotchas#typeof-window-checks
I've also updated the packageManager field in package.json. It looks like the pnpm-lock was generated using newer version than this field suggested. It didn't work properly using corepack for automatically managing pnpm version
=> Adjust isBrowser detection

src/lib/builders/select/index.ts, src/routes/docs/builders/select/preview.svelte
Having the arrow on the preview by default for a select feels odd. We can definitely keep it as an option for those who would want that and can possibly add an example of using the arrow within the `Select` docs!
I updated the styles of the preview as well to get rid of the bug and also position the popper appropriately for a select. I think it's best to avoid using `translate` css properties to move it around, and instead rely on the `positioning` options.
I'm not sure whether they would conflict with one another, but the CSS property definitely overrides any default positioning props. This is something we can investigate further.
=> fix: select preview

src/lib/builders/select/index.ts, src/routes/docs/builders/select/code.ignore-svelte, src/routes/docs/builders/select/preview.svelte
Things complete with this PR:
Some additional thoughts:
Some things I'm starting to realize is that if we want to truly provide an "out of the box" accessible component, with little thought from the user required to do so, we're going to have to take some more props and possibly add some additional elements to the builder.
For example, with a select, the "dropdown icon" should never be part of the accessibility tree, so by providing some default `icon` attributes that can be applied, more specifically `aria-hidden`. Of course, the beauty with builders is that a lot of things can be "opt-out"/"opt-in", by simply not using/spreading the element, but I think it would be nice to provide it.
If we want to align with [WAI-ARIA guidlines](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/) for …
=> feat(select): updates & touchups

.changeset/brave-mirrors-appear.md, src/lib/builders/select/index.ts
This update is 2 fold:
1. Update selectedText store to take in a number
2. Option now sets 2 additional data-* attributes (value and type) which is used when setting selectedText
- Value holds the option value
- Type holds the value type (string, number
Testing:
- Passed in an array containing both strings and numbers
- Asserted type-ahead works with numbers
- Mornitored the reactivitey of selectedText to ensure it's correct
=> selectedText should hold the correct value and support numbers

src/routes/docs/builders/select/code.ignore-svelte, src/routes/docs/builders/select/preview.svelte
This small PR fixes a style issue in the menu class for the select example, so it keeps its max size and show the scrollable section when a long list of elements are provided
=> Remove md:max-h-none class from select menu example

src/routes/docs/builders/switch/preview.svelte
This pull request adds just a small enhancement to the switch component by including the `transition-colors` class, which enables a smooth transition effect for the background color change.
=> feat: add color transition for switch component

.changeset/quick-carpets-arrive.md, src/lib/builders/select/index.ts, src/routes/docs/builders/select/code.ignore-svelte, src/routes/docs/builders/select/preview.svelte
- Adds optional label attribute to select
- When label is not present, uses textContent
- Sets type of selected to `unknown`
Motivations for this are: It's more intuitive to not pass in a label, coming from native select. But sometimes you'd want to override this, so we allow the label attribute to be set. This will be documented accordingly.
@huntabyte @geerew would love your thoughts on this!
Closes #35 & #39
=> refactor(select): label attr & unknown value

src/routes/+page.svelte
Fixes the copy button on the home page to npm install @melt-ui/svelte
=> Update copy in +page.svelte

src/lib/internal/actions/popper/popper.ts, src/lib/internal/actions/popper/popper.types.ts
This PR gives us the ability to disable the `useClickOutside` and `usePortal` actions for the internal `usePopper` action. It also enables the popper to accept options for the portal, defaulting to `'body'` if an element or other string isn't passed.
=> improve: popper options/config

src/routes/docs/builders/switch/code.ignore-svelte
Added the `transition-colors` class to `code.ignore-svelte` in the switch component.
=> fix: add transition-colors class to code.ignore-svelte

.changeset/new-trees-eat.md, package.json
**The issue:** packages that are auto-imported will always get `/index` appended to the end of their paths, which in most cases, isn't a valid path and will lead to runtime errors if left alone. 
Here's a quick example if you've never ran into this before:
This has become a _very_ common issue across Svelte packages because of SvelteKit's ["Packaging"](https://kit.svelte.dev/docs/packaging#typescript) documentation incorrectly stating to add `index`, rather than `index.d.ts`, to the `typeVersions` map. I think it may very well be a typo on their part.
We've [experienced this issue](https://github.com/skeletonlabs/skeleton/issues/1581) over at Skeleton and [added this fix](https://github.com/skeletonlabs/skeleton/pull/1587) not too long ago and it's been working great ever since!
=> fix: Adjusts `typeVerisons` map to fix incorrect auto-imported path

.changeset/thirty-numbers-drive.md, src/lib/builders/toggle/index.ts, src/routes/docs/builders/toggle/(snippets)/controlled.ignore-svelte, src/routes/docs/builders/toggle/(snippets)/disable.ignore-svelte, src/routes/docs/builders/toggle/(snippets)/index.ts, src/routes/docs/builders/toggle/+page.svelte
Updates documentation for [toggle](https://www.melt-ui.com/docs/builders/toggle), so it is up the same standard as `Accordion` and `Checkbox`
Also fixes #81 so it possible to disable the toggle after creation
=> Documentation for toggle and allow it disabled state to be changed

src/routes/(components)/code-block.svelte
fixes #96 by making the combining the scrolling elements, so it isn't two separate elements that are handles scrolling.
added a div around the code, as using the outer div for scrolling on the X axis gave unexpected behavior for the copy button
=> ensure scrollbars appear as expected on code previews

src/routes/docs/builders/dialog/(examples)/(drawer)/drawer.svelte
Hi, just a quick fix for the drawer example not having a focus trap.
=> Fix: focus trap not being applied to drawer example in dialog docu

src/routes/docs/builders/label/+page.svelte
A control that add a label to an input element. 
->
A control that adds a label to an input element.
=> Fix spelling error in label docs

src/routes/docs/builders/avatar/+page.svelte
The description text of the avatar was using the `Docs.P` component when it should be using the `Docs.Description` like the rest of the docs.
=> fix: avatar description

src/app.postcss
This fixes a theming issue where the scrollbars appeared too light compared to everything else and felt distracting.
This also fixes a minor problem where the example box corners were not rounded on the right side.
The background is left transparent. The scrollbar-thumb uses a lighter shade of the same color palette as the body.
=> fix: docs scrollbar styling

src/lib/builders/dropdown-menu/index.ts, src/routes/docs/builders/dropdown-menu/schemas.ts
Exposes a `preventScroll` option to the `createDropdownMenu` builder which is set to `true` by default to prevent scrolling while the dropdown is open.
Closes: #117
=> fix: prevent scroll on dropdown option

.changeset/modern-drinks-think.md, src/lib/builders/select/index.ts, src/lib/internal/helpers/array.ts, src/lib/internal/helpers/typeahead.ts, src/routes/docs/builders/select/(examples)/(preview)/preview.svelte, src/routes/docs/builders/select/(examples)/(preview)/tailwind.ignore-svelte, src/routes/docs/builders/select/+page.svelte, src/routes/docs/builders/select/schemas.ts
Refactor / enhance the `Select` builder to better align/share functionality with the `DropdownMenu` where applicable. 
Closes: #114
=> refactor (select): align select with menu & share typeahead

.changeset/friendly-houses-tease.md, src/lib/builders/tags-input/create.ts, src/lib/internal/helpers/builder.ts, src/routes/docs/builders/tags-input/(examples)/(preview)/tailwind.svelte
- Add new `attrribute` helper function to `createElHelpers()` which returns the full name (without the selectors)
- Fixes focusing on input when the $root is selected
=> Fix tag-input focus

.changeset/cuddly-turtles-develop.md, .prettierignore, playwright.config.ts, src/docs/previews/accordion/main/tailwind.svelte, src/lib/builders/combobox/create.ts, src/lib/builders/select/create.ts, src/lib/internal/helpers/array.ts, src/lib/internal/helpers/tests/array.spec.ts
This PR adds support for PageUp / PageDown keyboard controls when selecting items in the Combobox and Select builders.
It also fixes some files that weren't formatted correctly—causing the CI Linting job to fail.
- Replicated some entries from `.gitignore` to `.prettierignore`
- Formatted `playwright.config.ts` and `src/docs/previews/accordion/main/tailwind.svelte`
- Added `forward` and `back` array utilities for array traversal.
- [Combobox] Added cases for <kbd>Page Up</kbd> and <kbd>Page Down</kbd> to navigate +10 items and -10 items. The [aria spec](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) is vague about the increment of movement:
> Moves focus up an author-determined number of rows, typically scrolling so the top row in the currently visible set of rows becomes one of the …
=> [Select/Combobox] Support PageUp + PageDown keyboard controls

src/docs/content/installation.md
Installation of a package and it's dependencies should be done with `pnpm add` instead of `pnpm install`.
=> fixed pnpm add instead of pnpm install

src/docs/content/builders/tags-input.md
API References and Accessibility were nested inside Usage on this page
=> Wrong header level

src/docs/previews/avatar/main/css.svelte
Hi.
This adds the css example for the `avatar` component builder.
If this is acceptable, I wanted to gradually open P.R's for the remaining builders in a similar manner.
Qn: I sort of couldn't find a guide for the tw-css variables, e.g `line-height` and I'm not sure if you guys have your own custom ones. Any hint to where I could look to in the future would be appreciated.
As always, love what you're building. 💙
=> feat: css example for avatar

.changeset/chatty-hotels-fetch.md, src/docs/components/callout.svelte, src/docs/components/markdown/a.svelte, src/docs/content/builders/accordion.md, src/docs/data/builders/accordion.ts, src/docs/previews/accordion/disabled/css.svelte, src/docs/previews/accordion/disabled/tailwind.svelte, src/docs/previews/accordion/multiple/css.svelte, src/docs/previews/accordion/multiple/tailwind.svelte, src/lib/builders/accordion/create.ts, src/lib/builders/accordion/types.ts, src/markdown.postcss
This PR adds the missing `aria-controls` attribute to the accordion item trigger and adds previews that showcase a `multiple` accordion, as well as an accordion with a `disabled` item. I've also added a callout to the docs that mention the importance of wrapping the trigger in either a heading element or an element with the `role="heading"` and the `aria-level` attributes to ensure their components are accessible.
=> [Accordion] Finish adding aria attributes & add example previews

.changeset/modern-ligers-yawn.md, src/lib/index.ts
This may look weird, but this is how the type should look so that it applies to all the elements.
I've tested it with the reproductions and was no longer able to reproduce the type error after making this change.
=> Fix: Declaration merging type

.changeset/cyan-monkeys-return.md, src/lib/builders/tabs/create.ts
This is odd but it at least allows you to click and navigate the tabs with the arrow keys. The issue of not being able to go back to the tabs using the keyboard (unless I'm missing a setting) is still there.
Closes: #204
I do think we should discuss how to best approach supporting Safari's odd native behavior.
=> [Tabs] Force focus on click for buttons in safari

.changeset/giant-feet-flow.md, src/lib/builders/dialog/create.ts, src/lib/internal/helpers/is.ts
Resolves: https://github.com/melt-ui/melt-ui/issues/251
This is very straight forward changes for closing `Dialog` component only if the left click was clicked outside `content`.
=> fix: Dialog is closed on right button click

.changeset/lazy-pianos-kneel.md, src/lib/builders/checkbox/create.ts
Somewhere along the way, the `click` event listener got moved outside the `unsub`. This PR moves it back where it belongs :)
=> [Checkbox] Unsub checkbox click event

.changeset/silly-dodos-clean.md, src/docs/content/builders/combobox.md, src/docs/data/builders/combobox.ts, src/docs/previews/combobox/main/css.svelte, src/docs/previews/combobox/main/tailwind.svelte, src/lib/builders/combobox/create.ts
Closes: #277 
This PR adds a `label`  return to the Combobox builder to ensure the `aria-labelledby` of the input is set to an actual element. 
It's also to ensure the menu doesn't do the close/open flicker when clicking on the label or content within it when the menu is already open.
An alternative I considered was having the user import the label from the label builder separately, but then we'd also have to return an `id` or have them provide an `id` to use for the label and ensure they apply it to the label. This seemed like a bit much to expect. So I went with the more hands-off approach.
=> [Combobox] Fix Open/Close Flickering

.changeset/blue-pugs-learn.md, src/docs/content/builders/tooltip.md, src/docs/previews/tooltip/main/tailwind.svelte, src/lib/builders/tooltip/create.ts
Closes: #276
This PR reverts tooltip behavior to align with MDN's [ARIA tooltip role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role). Up to this point we had been a bit confused on how to handle the tooltip, but upon reading that pattern ~10 times, here's the conclusion we have come to:
If you expect the tooltip trigger to open the tooltip on click or touch, you shouldn't be using a tooltip, and should instead consider using a popover or collapsible. A common use-case I'd imagine you'd expect the tooltip content to open when pressing the trigger would be something like an "i" or info ⓘ icon, which is not appropriate as described here:
The appearance of the tooltip should be automatic, and not intentionally controlled by the user:
=> [Tooltip] Fix a11y attrs & behavior

.changeset/green-apes-explode.md, .eslintrc.cjs, src/lib/builders/hover-card/create.ts, src/stories/Collapsible/Collapsible.svelte
This rule prevent accidentally importing from `$lib/builders/*` given that the preferred way should be importing from `$lib` directly.
I've also fixed one occurence of this lint rule.
=> chore: add eslint rule to prevent imports from lib/builders

.changeset/forty-bags-confess.md, src/lib/builders/dialog/create.ts
Fixes internal behavior of dialog visibility to not require a trigger element to be present.
=> [Dialog] fix: dialog controlled open

.changeset/calm-flowers-watch.md, .changeset/real-brooms-rescue.md, src/docs/data/builders/accordion.ts, src/lib/builders/accordion/create.ts, src/lib/builders/context-menu/create.ts, src/lib/builders/context-menu/types.ts, src/lib/builders/dropdown-menu/types.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/menubar/types.ts
Prevent accidental imports of similar internal menu types by prefixing them with `_`
=> refactor: internal menu types

.changeset/soft-buses-flow.md, src/docs/previews/combobox/main/tailwind.svelte, src/lib/builders/combobox/create.ts, src/lib/builders/context-menu/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/dialog/types.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/popover/types.ts, src/lib/builders/select/create.ts, src/lib/builders/select/types.ts, src/lib/internal/helpers/elements.ts
This PR corrects some incorrect portal handling within our builders that portal. The logic became messy when we introduced the ability to pass a custom portal destination prop, which we weren't properly handling along with detecting if the element is already a descendant of a portal.
I'm gonna say portal about 300 times but here's a breakdown of the behavior to expect moving forward:
If you pass an `HTMLElement` or selector as the `portal` prop to any of the builders that support portals, your prop will take 100% priority. Meaning even if it's a `Menu` that's nested inside a dialog, but you pass in `"body"` as the `portal` prop to the menu, it's going to completely ignore the fact that it's already a descendent of a portal, and instead go straight to the body and become the dialog's …
=> Fix portalling issues

src/docs/content/builders/toast.md
This is the first approach to improve the docs of the toast builder, which will help users understand how to use the toast as global functionality.
After some testing, I found that it was better to introduce this in the "Usage" section, so that the first example remains a unit. Another alternative is to introduce this as an additional example. Let me know what you think!
PD: The formatter wouldn't allow me to place the `// ...path/to/file` comments at the top of each snippet.
=> Add a more complete explanation for global usage of the toast builder

.changeset/late-birds-beg.md, src/lib/builders/context-menu/types.ts, src/lib/builders/dropdown-menu/types.ts
Since we're using a builder for checkbox items, renamed the type to align with the other "builder" prop types.
=> refactor: menu types

.changeset/fuzzy-lamps-fail.md, src/docs/data/builders/tags-input.ts, src/lib/builders/tags-input/create.ts, src/lib/builders/tags-input/types.ts
Added `trim` option to the `input-tags` with default value to `true`.
=> feature: Add trim option to input-tags

.changeset/soft-files-fetch.md, src/lib/builders/select/create.ts, src/tests/select/Select.spec.ts
Currently, even when using the mouse to select an item, the trigger is refocused after selection. This can cause unexpected effects like screen jumps, etc.
This PR prevents the trigger from automatically being refocused when a selection is made using the pointer/mouse.
If this feels wrong, an option to `disableRefocusTriggerWhenUsingPointer` or something of that sort could also be used instead. I think an option to disable trigger refocus altogether is the solution, just when using a mouse.
=> [Select] Prevent trigger refocus when using mouse

src/docs/content/introduction.md
Updated the under construction warning in the introduction based on this info: https://discord.com/channels/1116682155809067049/1140452054888873994
> Once version 1.0 is released, semantic versioning will be followed,  (limiting breaking changes to major releases). Until then, breaking changes might happen on non-major releases.
> ^ this - we're prerelease. We do bump minor/patch versions. So right now, minor could consist of a breaking change where patch changes should not.
This makes it a lot clearer where breaking changes might happens and what the next goalpost is.
=> Clarified the warning in introduction.md

.changeset/funny-lizards-grow.md, src/lib/builders/select/create.ts, src/tests/select/Select.spec.ts
Updated related test accordingly.
Since this is an expected behaviour I did not changed the docs. 
Side note: I tested the Esc Key to close the Select menu, that may not be necessary or a separate test
=> feat(#389) after selecting, check multiple is false before closing select menu

.changeset/khaki-schools-hunt.md, src/lib/builders/dialog/create.ts
Moves the click outside handling logic from the `allowOutsideClick` handler in the focus trap action to its own action to align with the other builders with `clickOutside` logic.
=> fix: bug in dialog where `handleClose` was called twice on clickoutside

.changeset/dull-tomatoes-peel.md, src/lib/internal/helpers/scroll.ts
Should solve issue #419.
I used a `calc()` instead of simply adding the values because the body padding could be in any unit.
=> fix(#419) preserve body padding in removeScroll

src/docs/data/builders/tooltip.ts
=> fix: docs tooltip content events

.changeset/big-weeks-suffer.md, src/lib/builders/select/create.ts, src/lib/internal/helpers/elements.ts
Closes: #451
We had an extra portal action in there causing the portal to always be set to the body, regardless of the `portal` prop or parent portal situation. Removing the 2nd portal action solves the issue and it now works as expected.
=> Fix: select nested portal bug

.changeset/fair-bags-try.md, src/docs/data/builders/combobox.ts, src/docs/previews/combobox/main/tailwind/index.svelte, src/lib/builders/combobox/create.ts
Hey, I noticed that the `isSelected` function is currently always returning `false` since we're comparing two non-primitive object types. I changed the function to use `JSON.stringify()` instead which fixes that. Now the checkmark also shows up in the preview.
=> fix: Combobox isSelected function

package.json, pnpm-lock.yaml, src/lib/builders/combobox/create.ts, src/lib/internal/helpers/array.ts
- remove `deep-equal` and `@types/deep-equal` dependencies
- install `dequal` dependency
- replace usages of `deep-equal` with `dequal` in combobox `create.ts` and `array.ts` helper
I had a look at https://npmtrends.com/deep-equal-vs-dequal-vs-fast-deep-equal and compared the different options through:
- https://arve0.github.io/npm-download-size/#deep-equal
- https://arve0.github.io/npm-download-size/#fast-deep-equal
- https://arve0.github.io/npm-download-size/#dequal
Looking at the lockfile, I found more dependencies using `dequal` rather than `fast-deep-equal` under the hood, so I went with that. The lib is also much newer and had its latest commit in 2022. 
Also I remember lukeed (author of `dequal`) being part of the Svelte community, so there might be some overlap and an easier path …
=> refactor: migrate from deep-equal to dequal

.changeset/tough-cars-bake.md, src/lib/builders/menubar/create.ts
We previously weren't ignoring the menubar triggers within the `clickOutside` handler for the `menu` elements, meaning that before the click event made it to the trigger, we were setting the `activeMenu` to `''` causing the trigger to think that there wasn't already a menu open.
This PR fixed that issue by ignoring the menubar element and its descendants for `clickOutside` handling.
=> Fix: menubar trigger toggle bug

.changeset/ninety-buttons-smile.md, src/lib/builders/select/create.ts
Hey guys, this is the same as https://github.com/melt-ui/melt-ui/pull/464 but for the Select builder.
It's not letting me use object as values.
=> fix: Select isSelected function for single option.

.changeset/small-schools-bow.md, src/docs/components/table-of-contents/table-of-contents.svelte, src/docs/components/table-of-contents/tree.svelte, src/docs/previews/table-of-contents/main/tailwind/index.svelte, src/docs/previews/table-of-contents/main/tailwind/tree.svelte, src/lib/builders/table-of-contents/create.ts, src/lib/builders/table-of-contents/types.ts
**Changes:**
- add a mutation observer that checks if new headings were added or removed and updates the headings list if yes
- add the original heading node to the list of returned items so people have more control over how headings are displayed in the ToC
- update returns of builder function to match current structure
- update types
Addresses the following issues:
- Closes #476 
- Closes #450
=> [Table of Contents]: add mutation observer

.changeset/forty-weeks-bow.md, package.json
Add `repository` property to `package.json`
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository
The Renovate bot is not capturing release notes of Melt UI (even they are present in https://github.com/melt-ui/melt-ui/releases). This change will collaterally fix that issue.
You can read more details here: https://github.com/renovatebot/renovate/discussions/24304#discussioncomment-6944256
=> chore(package.json): add 'repository' property to `package.json`

.changeset/shaggy-fans-cheer.md, src/docs/data/builders/tooltip.ts, src/lib/builders/tooltip/create.ts, src/lib/builders/tooltip/types.ts
This PR adds `disableHoverableContent` as an option to the tooltip builder function. The behavior is consistent with same option in Radix and the implementation simply removes the content element from the polygon used for isMouseInTooltipArea. 
Default for the option is false, same as current behavior. I experimented with the docs example and the change works but I haven't implemented any rigorous testing. 
I also updated the documentation for the tooltip builder to reflect the new option.
=> tooltip builder `disableHoverableContent` option

src/docs/data/builders/slider.ts
The slider docs had incorrect types and was missing the API reference for the tick builder. This pull request fixes those issues.
=> fix: slider docs

.changeset/serious-avocados-cry.md, src/lib/builders/select/types.ts
The default value of the store can be undefined.
=> fix: select controlled store type

.changeset/tricky-plums-speak.md, src/lib/builders/menu/create.ts
When a menu such as `DropDownMenu` is opened there is initially no focussed item, which is expected.
Current behaviour is that when either the down or up arrow key are pressed, the first item is always highlighted. To my mind, down should focus the first item, while up should focus the last. This matches the current behaviour of the ComboBox component.
This PR implements what I think should be the expected behaviour.
=> Up key should focus last menu item if there is no selection

.changeset/pretty-numbers-remain.md, src/lib/internal/actions/melt/index.ts
- Issue: #568 
- Correct the JSDoc for melt action import in the file located at ```src/lib/internal/actions/melt/index.ts```
```
/**
* A special action for Melt UI's preprocessor `@melt-ui/pp`.
*
* @see https://www.melt-ui.com/docs/preprocessor
*
* @example
* ```svelte
* <script>
* 	const { builder, melt } = createBuilder();
* </script>
*
* <div use:melt={$builder} />
* ```
*/
```
```
/**
* A special action for Melt UI's preprocessor `@melt-ui/pp`.
*
* @see https://www.melt-ui.com/docs/preprocessor
*
* @example
* ```svelte
* <script>
* 	import { createLabel, melt } from '@melt-ui/svelte';
* 	const { elements: { root } } = createLabel();
* </script>
*
* <label use:melt={$root} />
* ```
*/
```
<br>
<br>
=> fix: JSDoc for melt action

.changeset/two-shrimps-notice.md, src/lib/builders/accordion/types.ts, src/lib/builders/combobox/types.ts, src/lib/builders/select/types.ts, src/lib/builders/toast/types.ts, src/lib/builders/toggle-group/types.ts
Added generics to exported types for accordion, select, toast and toggle group.
Fixes #538
=> Add generics to exported types

src/docs/content/builders/dialog.md, src/docs/content/controlled.md, src/docs/data/builders/dialog.ts
- Issue: https://github.com/melt-ui/melt-ui/issues/337
- Correct the Docs structure for ```createDialog()``` to get the uniformity between code and documentation
<br>
```
const { trigger, portal, overlay, content, title, description, close, open } = createDialog()
```
```
const {
elements: {
trigger, 
portal, 
overlay, 
content, 
title, 
description, 
close, 
open,
},
} = createDialog();
```
- **dialog.md** (src/docs/content/builders/dialog.md)
- **controlled.md** (src/docs/content/controlled.md)
=> fix: Dialog docs structure

.changeset/fair-yaks-travel.md, src/lib/builders/tooltip/create.ts, src/tests/tooltip/Tooltip.spec.ts
Tooltips with a `group` would prevent themselves from reopening again unless another tooltip in the same group was opened. This is due to the effect not cleaning up after the tooltip closes, so it stays in the "open tooltips map" forever.
This PR fixes the bug and adds a test to validate the fix.
=> Fix bug with Tooltip `group` parameter

.changeset/loud-bags-hug.md, src/lib/builders/slider/create.ts, src/lib/internal/helpers/attr.ts
This PR adds an aria-disabled attributes to the Slider's root element.
PS: sorry for doing 2 PRs, the old branch got messed up, so I deleted it.
=> Add `aria-disabled` to slider root

src/docs/content/builders/dialog.md
- Issue: **Dialog docs has incorrect highlighting** (Issue not created, Only PR)
- Correct dialog docs highlighting
<br>
- Change ```ts {2}``` to  ```ts {4}```
<br>
<br>
- **dialog.md** (src/docs/content/builders/dialog.md)
=> fix: Corrected dialog-docs highlight

src/docs/content/builders/toast.md
Very simple. Added code example in the doc to show how to override default values of the toaster for individual toasts.
Feel free to point me if there would be some other place that would benefit this info!
=> Added code example to override closeDelay for individual toast (see #554)

src/docs/content/builders/collapsible.md
- Issue: **Collapsible.md** generates warnings when clicked "**Collapsible**" in builder section (Issue not created, Only PR)
- Remove code which generates warnings
- Remove from **collapsible.md**: 
- ```export let previews```
- ```export let snippets```
<br>
- **collapsible.md** (src/docs/content/builders/collapsible.md)
<br>
=> fix: Corrected collapsible.md warnings

src/docs/previews/toggle/main/css/index.svelte
Add CSS example for Toggle. Part of https://github.com/melt-ui/melt-ui/issues/574
=> docs: add CSS example for Toggle

.changeset/eighty-items-march.md, src/lib/internal/actions/melt/index.ts
Partially fixes #606
Here's how the error will appear in the dev console:
We could keep it brief like this by only providing a link to the PP docs, or we can further add install instructions such as: 
`Install the preprocessor with: "npm install -D @melt-ui/pp"`
or
`Install the preprocessor with: "npx @melt-ui/cli init"`
=> fix: `melt` action now throws an error if it's used without the PP

src/docs/previews/toast/main/tailwind/index.svelte
this pr removes `closeDelay: 0` so that toasts in docs can close automatically using the default `closeDelay` (5000ms)
=> docs: make toasts close automatically

.changeset/empty-timers-enjoy.md, src/docs/constants.ts, src/docs/data/builders/menu.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts
closes #646
Expose the existing `disableTriggerRefocus` from the `menu` builder to the `dropdown menu` builder, and exit early on the 2 calls that refocuses the trigger on close
This causes deep links (hash links) to work properly as when the property is true, the focus will not be moved back to the trigger
=> Implement disableTriggerRefocus

.changeset/rotten-worms-warn.md, src/lib/builders/tooltip/create.ts
openTooltip is already being called in pointerevent and focus. The effect should only be concerned with closing the tooltip once the pointer leaves the grace area.
This fixes a couple issues:
1. onOpenChange was being called for every mouse move within the tooltip.
2. Overlapping grace areas were fighting over the group.
You can see the bug occurring in the Tooltip example here:
https://github.com/pauldemarco/melt-ui/tree/tooltip-group-bug
=> Avoid calling openTooltip on every mousemove.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/post-create.sh, .gitignore, package.json, pnpm-lock.yaml
For `Hacktoberfest`, I have been adding `GitHub Codespaces` / `VS Code Remote Containers` configuration for OSS projects to make it easier for contributors to the project to get up and running with the correct developer setup. Including the appropriate configuration for a project allows contributors to work entirely within a web browser via `GH Codespaces`, or inside of fully, and correctly configured containers on their own computer with `VS Code Remote Containers` (both of these use the same configuration, as `GH Codespaces` leverages the `Remote Containers` features under the hood).
For the `melt-ui` project, this configuration includes the following:
- Preinstalled `Node LTS`
- Preinstalled `ESLint`,  `Prettier`, `Tailwind CSS`, and `Svelte` extensions
- Preinstalled `playwright` …
=> feat(devcontainers): add the ability to use GitHub Codespaces and VS Code remote containers

src/docs/components/tooltip.svelte
Current behavior:
Fixed behavior:
=> Fix: Tooltip ghost hitbox in docs

.changeset/great-wasps-kneel.md, scripts/setupTest.ts, src/docs/previews/dropdown-menu/main/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/tests/dropdown-menu/DropdownMenu.spec.ts, src/tests/dropdown-menu/DropdownMenuTest.svelte, src/tests/select/Select.spec.ts, src/tests/select/SelectTest.svelte, src/tests/utils.ts
- Fixes a bug where we would refocus the subtrigger even if focus was within its submenu (double focusing).
- Add controlled `open` prop to submenus.
- Fixes a bug where the menus would not respect the `closeOnEscape` prop when it is set to false due to a submenu listener.
- Add tests for the `closeOnEscape` and `closeOnOutsideClick` props.
- Remove incorrect aria attributes from the context menu's trigger
- Fixed a bug where the `listbox` wasn't respecting the `closeOnEscape` prop & added a test for it
=> Menu & Listbox: improvements, bug fixes, tests

src/app.postcss
`color-scheme: dark` on `<html>` will make the browser's default elements dark to keep consistency with the Docs' theme overall. In this case, the only affected part will be the scrollbar.
=> Docs: CSS Color-Scheme dark

.changeset/green-worms-punch.md, src/lib/internal/helpers/focus.ts, src/tests/dropdown-menu/DropdownMenu.spec.ts, src/tests/popover/Popover.spec.ts
Since elements like the popover and other floating/conditionally visible elements do not exist in the DOM until after they are opened, there is a timing issue where it is possible that the element you wish to focus on open/close is not yet in the DOM which results in unexpected behavior.
This PR moves the execution of the `FocusTarget` function inside of the `sleep()` promise to ensure we give the DOM a chance to update before calling that function.
=> fix: timing issue with `handleFocus`

src/docs/data/builders/select.ts
Fix wrong element name in the builder data of `Select` docs.
=> Use properly cased hidden input element name

.changeset/itchy-drinks-taste.md, src/lib/internal/actions/escape-keydown/action.ts, src/lib/internal/actions/popper/action.ts
=> fix: prevent safari from minimizing when esc on dialogs

src/docs/content/builders/toast.md
Seemed unnecessary to have a ton of tailwind classes & other non-headless things inside the high-level setup guide.
=> [Toast]: Cleanup docs

src/docs/content/builders/dialog.md, src/docs/data/builders/dialog.ts
Closes #715 and another unreported issue (missing `portalled` element in the [API reference](https://www.melt-ui.com/docs/builders/dialog#:~:text=for%20the%20elements.-,Elements,-Open%20popover))
=> Docs: Dialog fixes

.changeset/rude-glasses-reflect.md, src/lib/builders/listbox/create.ts, src/lib/internal/helpers/is.ts
Closes: #729 as a patch fix for now.
In the future, maybe it's worth exploring rather than relying on if the element is truly a `<button />` or not and instead maybe accept a prop to the listbox builder for the specific type of listbox we're working with (combobox or select) to clean this up a bit.
Would cover those cases where someone is using say a `<div role="button />` instead of a `<button />`.
=> fix: space to select select options

.changeset/purple-pumpkins-sit.md, src/lib/builders/listbox/create.ts
=> Fix: Key events in Select don't work in Safari

src/routes/docs/builders/[name]/+page.svelte
Changed `overflow-visible` to `overflow-x-visible overflow-y-auto` to prevent TOC content (Calendar builder and maybe more?) from overflowing at the bottom of the screen and become unreachable. (1920x1080px screen)
Screenshot :
=> Prevent TOC content from being unreachable (overflow below screen edge)

src/docs/data/builders/menu.ts
The Context Menu createContextMenu ) is missing 3 elements (item, group, groupLabel). Description I added as a placeholder. So please tell me a description of these elements so I can update them. I think there should be a preview component for these elements so should I open an issue?
=> #736 Docs: missing elements in API reference for Context Menu

src/docs/data/builders/slider.ts, src/lib/builders/slider/create.ts
This PR adds the `data-value` attributes to the `tick`. This improves customizability, like only showing certain ticks, for example. I also added `data-value` to the `thumb` for consistency (I'm aware `aria-valuenow` exists, just thought it'd be nice to be consistent).
=> Slider: add `data-value` attribute to `tick` and `thumb`

.changeset/fifty-cats-collect.md, src/lib/builders/date-picker/create.ts, src/lib/builders/date-range-picker/create.ts
Closes: #777 
Fixes reactivity issues when updating certain `option` stores related to the date picker.
Ideally in the near future, I can determine a better way to handle passing these stores around and improve the composability.
=> Fix: Date Picker popover prop reactivity

.changeset/afraid-chefs-talk.md, src/docs/data/builders/calendar.ts, src/docs/data/builders/range-calendar.ts, src/lib/builders/calendar/create.ts, src/lib/builders/range-calendar/create.ts, src/lib/internal/helpers/date/calendar.ts
Removes an unnecessary data attribute applied to the calendar cells.
=> chore: remove unnecessary attributes in calendar

src/docs/constants.ts
The `positioning` prop takes a `FloatingConfig` object, which has a key called `placement`.
=> docs: Fix typo `positioning` → `placement`

.changeset/happy-rings-cover.md, src/lib/builders/calendar/create.ts, src/lib/builders/dialog/types.ts, src/lib/builders/link-preview/types.ts, src/lib/builders/listbox/types.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/types.ts, src/lib/builders/pin-input/types.ts, src/lib/builders/popover/types.ts, src/lib/builders/tooltip/types.ts, src/lib/internal/helpers/id.ts
To override ids on some components, you have to provide ids for all elements. This PR fixes that by making the `ids` prop `Partial`.
=> fix: `ids` prop is not `Partial`

.changeset/silent-doors-impress.md, src/lib/builders/dialog/create.ts
fix: `aria-modal` attr TS type matches the type of a Svelte Element
Fixes #787
=> fix: aria-modal attr type

.changeset/mean-forks-sin.md, src/docs/data/builders/range-calendar.ts, src/lib/builders/range-calendar/create.ts
We don't update the `value` until both the `start` and `end` are populated, which makes sense considering the value is a range that is incomplete without both.
However, sometimes you may want access to the current `startValue` / `endValue` individually, so we return those derived stores (which we already use internally) to be used.
=> feat: return `startValue` & `endValue` from range calendar

.changeset/tasty-seahorses-listen.md, src/lib/builders/checkbox/create.ts
When using [the example code from the melt-ui docs](https://www.melt-ui.com/docs/builders/checkbox), with a disabled checkbox:
```js
const {...} = createCheckbox({ disabled: true });
```
The resulting output is a disabled `<input />` inside of a non-disabled `<button />` (though it's pretty clear that the intent was to disable the button, because it does get `data-disabled="true"`:
```html
<button data-disabled="true" data-state="unchecked" type="button" role="checkbox" aria-checked="false" aria-required="false" data-melt-checkbox="">
<input type="checkbox" aria-hidden="true" hidden="true" tabindex="-1" name="" value="disabled" disabled="" data-melt-checkbox-input="" style="position: absolute; opacity: 0; pointer-events: none; margin: 0px; transform: translateX(-100%);">
</button>
```
As …
=> Checkbox: add `disabled` prop to button that wraps input

.changeset/strong-flowers-hunt.md, src/lib/builders/slider/create.ts
The `aria-disabled` prop should be only be present on the thumb, where the "slider" role exist.
=> fix(slider): remove `aria-disabled` from root

src/docs/data/builders/tags-input.ts
- change wrong default of `true` to `false` for `addOnPaste` in `tags-input.ts`
The default value of `addOnPaste` is defined as `false` here: https://github.com/melt-ui/melt-ui/blob/26e41134169528e22451782259be0b2506bdaec0/src/lib/builders/tags-input/create.ts#L34
BUT it was showing as `true` in the documentation on the website.
Closes https://github.com/melt-ui/melt-ui/issues/828
=> docs: Tags Input mentions that addOnPaste is true by default but it doesn't work

.changeset/swift-dragons-drop.md, src/lib/internal/helpers/builder.ts
The return type of `$thumb()` is incorrectly typed as a function, even though it is not.
=> Slider: Fix return type of `thumb` builder

src/docs/content/installation.md
A custom version of `sequence` (to fix source maps) is now built into the `@melt-ui/pp` package, so we don't need `svelte-sequential-preprocessor` anymore.
=> docs: Update PP installation guide

.devcontainer/post-create.sh
While attempting to open a dev container in VS Code on macOS, I encountered a build failure due to an `ERR_PNPM_LINKING_FAILED` error. This issue was caused by the pnpm store path being set to `/workspaces/melt-ui/.pnpm-store/v3`. To resolve this, I have explicitly set the pnpm store directory in the `post-create.sh` script.
This pull request is a bug fix aimed at preventing the `ERR_PNPM_LINKING_FAILED` error when building the container, ensuring a smoother development setup for macOS users.
- Modified the `post-create.sh` script to set the pnpm store directory explicitly.
Please note that this change has not been tested on Linux or Windows systems. If you are using these operating systems, please test the changes and provide feedback.
=> fix: failed opening dev container on macos

.changeset/gorgeous-paws-do.md, src/lib/builders/toast/create.ts
aria-live property on toast `content` store was returning as `string` where ts expects `"off" | "assertive" | "polite"`. Similar to #839.
fixes ex:
=> fix(Toast): use as const for `'assertive' | 'polite'` aria-live type

.changeset/slow-apples-fry.md, src/lib/internal/actions/escape-keydown/action.ts
> A boolean value indicating that events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree. If not specified, defaults to false.
This means that the top-level listener was running before any listener(s) that actually should be run. Because of this, it was impossible for a "child" listener to intercept an `ESC` keydown event & have it not affect the rest of the page.
Closes #842
=> fix(escape-keydown): remove `capture` listener

.changeset/shy-walls-buy.md, src/lib/builders/context-menu/create.ts, src/lib/builders/date-picker/create.ts, src/lib/builders/date-range-picker/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/dialog/types.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/link-preview/types.ts, src/lib/builders/listbox/create.ts, src/lib/builders/listbox/types.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/popover/types.ts, src/tests/combobox/Combobox.spec.ts, src/tests/combobox/ComboboxTest.svelte, src/tests/context-menu/ContextMenu.spec.ts, src/tests/date-picker/DatePicker.spec.ts, src/tests/date-picker/DatePickerTest.svelte, src/tests/dialog/Dialog.spec.ts, src/tests/dropdown-menu/DropdownMenu.spec.ts, src/tests/dropdown-menu/DropdownMenuTest.svelte, src/tests/link-preview/LinkPreview.spec.ts, src/tests/popover/Popover.spec.ts, src/tests/select/Select.spec.ts, src/tests/select/SelectTest.svelte
This PR exposes an `onOutsideClick` prop for all components where we handle "outside click" events. This is a prop rather than an event dispatch as these events are handled at the `document`, so dispatching them from a random element would be weird.
If you call `event.preventDefault()` inside this handler, it will cancel all default behavior applied by Melt.
I also added some tests for this functionality.
=> feat: expose `onOutsideClick` handler

.changeset/tricky-cougars-burn.md, src/lib/builders/progress/types.ts
The purpose of this PR is to update the types of the `value` prop used by the `Progress` builder to allow for passing a `null` value to effectively be able to set the progress in the `indeterminate` state, as the implementation suggests:
https://github.com/melt-ui/melt-ui/blob/74e868522ec869ed8a1cdb2192f41a9bd881bd8e/src/lib/builders/progress/create.ts#L38
=> fix(progress): allow null value for indeterminate state

.changeset/loud-readers-count.md, package.json, pnpm-lock.yaml
- upgrade `nanoid` from 4.0.2 to 5.0.4
Keep up to date with dependencies that are consumed by users of the lib.
See breaking changes listed in https://github.com/ai/nanoid/blob/main/CHANGELOG.md#50.
=> chore: upgrade nanoid to v5

.changeset/quiet-ads-allow.md, src/lib/internal/helpers/date/calendar.ts, src/lib/internal/helpers/date/tests/calendar.spec.ts, src/tests/date-picker/DatePicker.spec.ts
Fixes #868.
I've updated the extraDaysArray variable to add days starting from 1, not 0 which was causing the duplication outlined in the issue and I've added some tests for this particular edge case.
I've also added some defaults for some DatePicker tests which were breaking when I first forked the repository without making any modifications in the code.
Let me know if I need to make any other changes. Thanks!
=> Fix(calendar): extraDays array should add days starting from 1

.changeset/seven-pillows-turn.md, src/lib/builders/menu/create.ts, src/tests/dropdown-menu/DropdownMenu.spec.ts
fix #867.
When the page is first loaded, there is no need to focus on the trigger even if $rootOpen is false.
However, when rootActiveTrigger is set at the time it is mounted, the effect will be executed and the trigger will be focused.
Since we only need to pay attention to whether the menu is closed or not, we did not need to monitor the rootActiveTrigger.
=> fix(menu): focus on the trigger when rootActiveTrigger is defined

.changeset/giant-buckets-bake.md, src/docs/data/builders/tooltip.ts, src/lib/builders/tooltip/create.ts
Closes: #888 
Adds the `data-state` attributes to the `trigger` and `content` of the tooltip.
=> fix: missing tooltip data-attrs

.changeset/lemon-shrimps-tan.md, src/docs/data/builders/menubar.ts, src/lib/builders/menubar/create.ts, src/lib/builders/menubar/types.ts
Related: #821
When using the menubar, you need to decide on a per-menubar basis whether to prevent scroll, rather than on a per-menu basis. Doing so on a per-menu basis causes significant lag and performance hits if one menu in the menubar does preventScroll and another doesn't.
A `preventScroll` prop & option has been added to the `createMenubar` builder, while we have removed the prop from the `createMenu` builder that the menubar builder returns, as it will inherit this prop from the menubar.
=> fix: menubar `preventScroll`

package.json, pnpm-lock.yaml
- upgrade `tailwind-merge` from 1.14.0 to 2.2.0
v2 changes are listed on https://github.com/dcastil/tailwind-merge/releases/tag/v2.0.0
According to https://github.com/dcastil/tailwind-merge/blob/v2.0.0/docs/changelog/v1-to-v2-migration.md, "No changes to twMerge and supported Tailwind CSS versions" were made.
=> chore: upgrade tailwind-merge to v2

.changeset/lazy-zoos-itch.md, src/docs/pp.js, src/docs/pp.spec.ts, src/docs/previews/slider/main/tailwind/index.svelte, src/docs/previews/slider/range/tailwind/index.svelte, src/docs/previews/slider/rtl_horizontal/tailwind/index.svelte, src/docs/previews/slider/rtl_vertical/tailwind/index.svelte, src/docs/previews/slider/ticks/tailwind/index.svelte, src/docs/previews/slider/vertical/tailwind/index.svelte, src/lib/builders/slider/create.ts, src/lib/internal/helpers/builder.ts, src/routes/(landing-ui)/slider.svelte, src/tests/slider/RangeSlider.svelte, src/tests/slider/Slider.svelte
This pr changes and `thumb` and `tick` elements from being functions to just arrays of builders.
```html
{#each { length: $ticks } as _}
<span use:melt={$tick()} />
{/each}
{#each $value as _}
<span use:melt={$thumb()} />
{/each}
{#each $thumbs as thumb}
<span use:melt={thumb} />
{/each}
{#each $ticks as tick}
<span use:melt={tick} />
{/each}
```
Limitations:
The melt pp does not seem to work with the new loop syntax. I added TODOs to replace the loops later on when this issue is fixed.
Update:
The pp works fine. The problem is in the docs itself.
=> Slider: Refactor Thumb and Tick

.github/workflows/preview.yml, .github/workflows/production.yml
- On the Melt repo, go to **Settings**
- On the left side, select **Environments**, then **Preview** (if `Preview` is not present, select **New environment** and create it)
- Check the **Required reviews** checkbox, and add yourself and hunter to the reviewers (later on, we can create a Team where anyone on that team can approve preview deployments)
- Click on **Save protection rules**
And with that, you're all set!
=> chore: Replace CF Pages integration with `refined-cf-pages-action`

.github/workflows/preview.yml, .github/workflows/production.yml, src/routes/docs/[...slug]/+page.server.ts
The idea here is to only expose the `GITHUB_TOKEN` during production builds. `GITHUB_TOKEN` was changed to a dynamic env var so that preview builds don't fail when it's missing.
=> chore: make `GITHUB_TOKEN` dynamic for docsite builds

.changeset/warm-donkeys-eat.md, src/lib/builders/date-field/create.ts, src/tests/date-field/DateField.spec.ts
Previously when User typed in `00` as the value for minute and second segment it would not get registered. This fixes the issue and allows `00` as a valid input for minute and second segment but disallowing for the other fields.
=> allow 00 as values in minute and second segment for date field

src/docs/data/builders/slider.ts
fixed docs slider types to match the actual typescript types
=> fix: docs slider types

src/docs/data/builders/date-field.ts
The docs include the wrong param names. Instead of the `next` param it mentions `prev`.
``` ts
// melt-ui/melt-ui/src/lib/internal/helpers/overridable.ts
export type ChangeFn<T> = (args: { curr: T; next: T }) => T;
```
=> docs: fix wrong description of ChangeFn

.changeset/giant-spoons-sleep.md, src/lib/builders/tabs/create.ts
Fixes the type of `type` in the tabs builder which was conflicting with svelte button types
=> fix: type of `type` in tabs builder

src/docs/data/builders/tags-input.ts
In the Tags Input builder docs `denied` prop was still referenced as `disallowed` even though it was changed on: https://github.com/melt-ui/melt-ui/commit/072e30053a4b35a39cce5e5a7f8234fe2e7da14a
=> docs: Fix 'denied' prop name on Tags Input builder docs

.changeset/silly-bananas-train.md, src/lib/builders/tooltip/create.ts, src/lib/internal/helpers/is.ts, src/tests/tooltip/Tooltip.spec.ts, src/tests/tooltip/Tooltip.svelte
Closes #945 
This PR addresses a bug where the tooltip content would remain open if a user scrolls outside of it, which is unexpected behavior. I've added a listener to the `window` when the content is mounted to handle scroll events that occur outside the content. If the tooltip content is scrollable, we don't close when scrolling that content, only other scroll targets.
I've added tests for this functionality & patched some of the tooltip tests that are currently being skipped to now work. A `setup` test helper for the tooltip tests.
=> fix: Close tooltip on scroll

src/docs/components/nav/sidebar-nav.svelte
On vertically smaller screen sizes, only a small portion of the sidebar is visible due to the size of the height each nav item takes up.
This PR decreases that size slightly, allowing more items to be visible at a time.
=> docs: decrease sidebar font size

.changeset/spotty-ants-kiss.md, src/lib/builders/toggle-group/create.ts
The ToggleGroup onValueChanged was not working properly when items were being added. I noticed both the v.curr and v.next values were always the same.
Upon further examination, I noticed that when removing items the v.curr and v.next were correct.
Digging into the code, we can see that when items are removed, a copy of the array is returned, but when an item is added, the same instance of the array is returned.
This fix simply returns a copy of the array when an item is added.
I can confirm my use case of "Set a max to the toggled items" now works perfectly.
=> [ToggleGroup] Fix onValueChanged when adding items

.changeset/great-toys-look.md, src/lib/builders/toast/create.ts
type property on toast close element was returning as string where ts expects `'button' | 'reset' | 'submit' | null | undefined`. Similar to https://github.com/melt-ui/melt-ui/pull/859.
fixes ex:
=> fix(Toast): use as const` for close element `type` attribute

.changeset/forty-beers-reply.md, src/lib/internal/actions/interact-outside/action.ts, src/tests/dialog/Dialog.spec.ts
We're now tracking the target of the `pointerdown`/`mousedown`/`touchstart` events to determine if we should close the modal or not.
Before:
https://github.com/melt-ui/melt-ui/assets/64506580/23f0c9e6-cebb-4112-bfbe-8d580dd76031
After:
https://github.com/melt-ui/melt-ui/assets/64506580/2f3587c4-88c8-46ae-bb9d-fcdd349f2757
Closes: #750
Todo:
=> fix: interact outside pointerup/mouseup issue

src/lib/builders/context-menu/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/link-preview/types.ts, src/lib/builders/listbox/create.ts, src/lib/builders/listbox/types.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/popover/types.ts, src/lib/internal/actions/modal/types.ts, src/lib/internal/actions/popper/action.ts, src/lib/internal/actions/popper/types.ts, src/lib/internal/helpers/ignore.ts, src/lib/shared/index.ts, src/tests/context-menu/ContextMenu.spec.ts, src/tests/popover/Popover.spec.ts
This PR updates existing builders to use the new `useModal` action, which has improved the handling of outside interaction events across various platforms. 
Closes: #992
=> fix: Interact outside issues

src/docs/components/tooltip.svelte
This issue is that the tooltip content transitions all properties which includes the `left` css property, so when the content is opened or closed, and because we don't unmount the tooltip content, the content starts as visually hidden and is placed on the left side of the page, and then gets transitioned from the initial position to the trigger position.
This is easily solved by only transitioning `opacity`. 
On a different note, I find it odd that when the content is closed but not unmounted, that it has the same `top` value as when it was mounted, but it resets the `left` value. 
Before
https://github.com/melt-ui/melt-ui/assets/53095479/b87e5566-afb9-4dd3-862a-94f7813bcee7
After
https://github.com/melt-ui/melt-ui/assets/53095479/66b6b39a-db7f-4ca5-90e7-0a2485dd130e
=> fix(docs): tooltip transition

.changeset/proud-pigs-pump.md, src/lib/builders/toolbar/create.ts, src/tests/toolbar/Toolbar.spec.ts, src/tests/toolbar/ToolbarTest.svelte
At present, the tabindex attribute of toolbar items is initialized only for group items, never for simple buttons or links.
As a result, when there is no group item, or the first item is a button/link, the toolbar becomes inaccessible by keyboard navigation.
This patch fixes the problem and introduces a comprehensive suite of regression tests, both by changing the order of items and by removing group items entirely.
=> fix(Toolbar): set correct tabindex for buttons and links

.changeset/silver-rivers-draw.md, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts
closes #1005, https://github.com/huntabyte/bits-ui/issues/340
The following issue applies to the following components:
- popover
- menu
- date range picker
- date picker
- link preview--activated by keyboard
- tooltip--activated by keyboard
- combobox
- select
In the instance of the popover, if we mount the content using else if condition blocks and have an out transition on the content, if you click outside the content and if that triggers an unmount from a parent component (i.e. clicking on a link that unmounts the page), the out transition plays while the content jumps to the top left of the page.
https://github.com/melt-ui/melt-ui/assets/53095479/b3494fd6-64f4-4140-9244-6cbd22cc86ed
This only happens if the content is in an **else if** block, for example:
```svelte
{#if $open && …
```
=> fix: interact outside transition out bug during unmounting  #1005

src/docs/components/tooltip.svelte
The tooltip used in the docs is always mounted, and since the positioning strategy is by default `absolute`, whenever you scroll, the tooltip content position gets recalculated. This can be easily avoided by setting positioning strategy to `fixed`
https://github.com/melt-ui/melt-ui/assets/53095479/cc79cffb-6276-4b77-b31a-2def324b93be
https://github.com/melt-ui/melt-ui/assets/53095479/4c77059c-eefb-4e76-b1a1-67b450e3bf99
=> fix(docs): improved mounted tooltip content performance during scroll

.changeset/pretty-kiwis-search.md, src/lib/builders/listbox/create.ts
=> fix: `multiple` change function `curr` and `next` always being equal

.changeset/large-countries-laugh.md, src/lib/builders/context-menu/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/link-preview/types.ts, src/lib/builders/listbox/create.ts, src/lib/builders/listbox/types.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/popover/types.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/actions/modal/action.ts, src/lib/internal/actions/modal/types.ts, src/lib/internal/actions/popper/action.ts, src/lib/internal/actions/popper/types.ts, src/lib/internal/helpers/attr.ts, src/lib/internal/helpers/elements.ts, src/lib/internal/helpers/ignore.ts, src/lib/shared/index.ts, src/routes/(landing-ui)/search.svelte, src/tests/context-menu/ContextMenu.spec.ts, src/tests/popover/Popover.spec.ts, src/tests/portal/PortalNested.spec.ts
Closes: #992 
Alright, I was able to pinpoint the root of the issue with the previous iteration of this, which had to do with the `getPortalDestination` function's logic being confusing (even though I originally wrote it).
If we find a portalParent and the user didn't specify a manual override via the `portalProp`, we want to return `null` for the portal so that it stays within it's appropriate `portalParent`.
The docs search works as expected and doesn't close on the input being clicked twice or anything else weird that I'm able to see.
I'll be in and out this week as I'm traveling for work, so feel free to make any modifications/add any additional regression cases you can think of to this PR to get it merged and have those other issues addressed.
=> fix: portal & outside interactions (the right way)

.changeset/unlucky-countries-argue.md, src/docs/content/builders/context-menu.md, src/docs/content/builders/dropdown-menu.md, src/docs/data/builders/context-menu.ts, src/docs/data/builders/dropdown-menu.ts, src/docs/data/builders/menu.ts, src/docs/previews/context-menu/modal/tailwind/index.svelte, src/docs/previews/dropdown-menu/modal/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts
This PR adds an optional `overlay` builder element to the Dropdown & Context Menus to enable modal behavior where outside interactions can be blocked by the overlay while the menu is open.
Closes #959
=> feat: Menu Overlays

.changeset/breezy-dots-happen.md, .changeset/six-vans-love.md, src/docs/previews/scroll-area/main/tailwind/index.svelte, src/lib/builders/scroll-area/scrollbars.ts, src/tests/scroll-area/ScrollArea.spec.ts, src/tests/scroll-area/ScrollAreaTest.svelte
This PR fixes issues with the style of `scrollbarX` due to a missing parenthesis. It also fixes the case where `type: 'hover'` scrollbars would still display even when the content isn't overflowing.
=> fix: ScrollbarX issues

.changeset/strange-actors-guess.md, src/lib/builders/listbox/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/actions/floating/action.ts, src/tests/combobox/Combobox.spec.ts
closes #1058, #1039
https://github.com/melt-ui/melt-ui/assets/53095479/a1ee3f6c-badf-4fac-8049-8a90ea73249c
This has been an ongoing issue with multiple components--the content jumps to the top left of the page when you unmount the component externally while the content is open when using an out transition on the content and when using an else if block to render the content.
The previous workaround that solved this issue for all components but the tooltip was to introduce `sleep(0)` before setting the `$open` state to `false`. So when the component get unmounted externally while the content is open, svelte can unmount the whole component instead of, for some reason, starting the transition out of the content, at which stage the content loses its anchor and causes the content to jump to …
=> fix: clean dead reference to floating content

.changeset/perfect-otters-shout.md, src/lib/builders/calendar/create.ts, src/lib/builders/date-picker/create.ts, src/tests/calendar/Calendar.spec.ts, src/tests/date-picker/DatePicker.spec.ts, src/tests/date-picker/DatePickerTest.svelte, src/tests/range-calendar/RangeCalendar.spec.ts
Closes #1074 
I initially added the code to sync the options in the range date picker to but i just now realized while writing the tests that the range date picker doesn't expose the calendar options like `numberOfMonths`, `fixedWeeks` or `weekStartsOn`. I have everything stashed locally so if you prefer that i expose those props in another PR and then sync them i can do it. In the meantime here it is.
EDIT: i've also fixed a couple of test names in my two old PRs
=> fix: datepicker not syncing with calendar

.changeset/popular-meals-walk.md, src/docs/data/builders/combobox.ts, src/docs/data/builders/link-preview.ts, src/docs/data/builders/menu.ts, src/docs/data/builders/popover.ts, src/docs/data/builders/select.ts, src/docs/data/builders/tooltip.ts, src/docs/utils/content.ts, src/lib/internal/actions/floating/action.ts, src/tests/date-field/DateField.spec.ts
This PR introduces small yet mighty improvements to the "floating" content and arrows, which apply `data-side` and `data-align` attributes to the various "floating" elements containing the _true_ positioning of the element after the floating UI computation.
`data-side` can be one of - `'top' | 'left' | 'bottom' | 'right'`
`data-align` can be one of - `'start' | 'end' | 'center'`
The arrow component just receives the `data-side` attribute, so you can easily adjust the style of the arrow depending on the side it's actually rendered on.
=> feat: `data-side` & `data-align` for floating content

.changeset/silly-eels-search.md, src/lib/builders/listbox/create.ts, src/lib/builders/popover/create.ts
issue https://github.com/melt-ui/melt-ui/issues/1086 describes the effect running twice since we update both the open and activeTrigger stores. The issue was already fixed in PR https://github.com/melt-ui/melt-ui/pull/1087, but we can avoid running the effect twice by not updating the active trigger store if it's the same as the previous. Just a slight performance improvement.
=> performance improvement: avoid effect multiple runs

.changeset/many-rockets-cough.md, src/lib/builders/dialog/create.ts, src/lib/builders/popover/create.ts
closes https://github.com/melt-ui/melt-ui/issues/1091
Focus trap should not deactivate when escape is pressed if the prop `closeOnEscape: false` is provided. 
https://github.com/melt-ui/melt-ui/assets/53095479/5ffbea4c-f9e1-46b7-b0b8-fbe4c9bba2c3
https://github.com/melt-ui/melt-ui/assets/53095479/57633812-b6aa-40a7-b068-8459fc1a01d5
https://github.com/melt-ui/melt-ui/assets/53095479/167c7346-a1ac-4263-b60d-a444fa95d4eb
https://github.com/melt-ui/melt-ui/assets/53095479/73d05257-ddc9-4eb3-96fb-2b8de71675dd
=> fix(dialog, popover): focus trap deactivates on escape provided `closeOnEscape: false`

.changeset/sharp-files-deliver.md, src/lib/builders/context-menu/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts
closes https://github.com/melt-ui/melt-ui/issues/1086
See the above issue for the full details. 
The action cleanup functions don't run in the following condition:
- When setting the cleanup function after a promise (i.e. tick())
- When the effect runs twice "concurrently", which can happen when updating more than 1 store that the effect depends on
Let's assess what happens with the following popover code assuming forceVisible is `false` and so `isVisible` matches the open state. Also, for context, the popover `handleOpen` sets the open state to true and sets the active trigger as well, which causes the following action to run twice "concurrently".
```typescript
const content = makeElement(name('content'), {
action: (node: HTMLElement) => {
let unsubPopper = noop;
const unsubDerived = …
```
=> fix action cleanup function not running due to race condition and promises

.changeset/fifty-pigs-promise.md, src/lib/builders/dialog/create.ts, src/lib/builders/popover/create.ts, src/tests/dialog/Dialog.spec.ts, src/tests/popover/Popover.spec.ts
closes https://github.com/melt-ui/melt-ui/issues/1084
Focus trap should not deactivate on click outside if the prop `closeOnOutsideClick: false` is passed. To make sure that this issue https://github.com/melt-ui/melt-ui/issues/452 doesn't occur, we need to allow outside clicks in the focus trap--this doesn't affect the content getting closes.
https://github.com/melt-ui/melt-ui/assets/53095479/f4e9d207-dc24-455a-93ed-1c0cee4baa9f
https://github.com/melt-ui/melt-ui/assets/53095479/3bc5c44d-9810-484b-8456-792eb9754fa5
https://github.com/melt-ui/melt-ui/assets/53095479/55c63c71-d823-4d4f-bc7f-6ea719cf412b
https://github.com/melt-ui/melt-ui/assets/53095479/d85f6682-aa51-4efb-a1c6-40b831e96471
=> fix(dialog,popover):focus trap `closeOnOutsideClick: false` bug

.changeset/giant-queens-drive.md, src/lib/builders/listbox/create.ts
Fix menu close by Enter event within composition session.
https://github.com/melt-ui/melt-ui/assets/6259797/1a8c9142-948f-44d6-ae79-f1cda1443111
https://github.com/melt-ui/melt-ui/assets/6259797/aabe1731-feb3-4e42-95c7-101b770f7a13
=> fix(combobox): menu close within composition session

src/tests/dialog/Dialog.spec.ts, src/tests/dialog/DialogTest.svelte
This prevents regression of https://github.com/melt-ui/melt-ui/pull/845
Added tests to allow a child to intercept escape keydown events without the dialog (or any other builder relying on `useEscapeKeydown()`) getting closed.
=> test: allow intercepting escape keydown events

.changeset/witty-pandas-argue.md, src/lib/builders/popover/create.ts
Prevent potential memory leak on popover overlay portal. Should cleanup portal action in the case that the `portal` store updates.
=> fix: overlay portal cleanup - prevent memory leak

src/docs/components/tooltip.svelte
We should not keep the tooltip always mounted. 
After this PR https://github.com/melt-ui/melt-ui/pull/1080, this will cause the tooltip to always stay in the stack and so escape key presses will behave unexpectedly. 
So for example, in the docs we have 2 tooltips using this component--the theme switcher and search. Since the tooltips are always mounted, the first tooltip when open will not react to an escape key press since it's not in the top of the stack.
=> docs: fix tooltip always mounted

src/docs/components/nav/mobile-nav.svelte, src/docs/content/builders/dialog.md, src/docs/previews/dialog/alert/css/index.svelte, src/docs/previews/dialog/alert/tailwind/index.svelte, src/docs/previews/dialog/controlled/css/index.svelte, src/docs/previews/dialog/controlled/tailwind/index.svelte, src/docs/previews/dialog/drawer/css/index.svelte, src/docs/previews/dialog/drawer/tailwind/index.svelte, src/docs/previews/dialog/main/css/index.svelte, src/docs/previews/dialog/main/tailwind/index.svelte, src/docs/previews/dialog/nested/css/index.svelte, src/docs/previews/dialog/nested/tailwind/index.svelte, src/tests/dialog/DialogNestedTest.svelte
We should not keep the dialog portalled always mounted. This is fixed in this PR https://github.com/melt-ui/melt-ui/pull/1080, however when using `forceVisible: true`, we should keep the portalled element inside the if block, not outside.
This especially creates issues when using sibling portals. For example, if we use 2 dialogs that should be nested inside each other while using sibling portals and we have the nested dialog in our svelte file above the top dialog. When opening the nested dialog, the nested dialog is going to be "behind" the main dialog. This is because the portal of the nested dialog was mounted first and so the main dialog's portal appears after in the DOM which takes precedent z-index wise even if you give both dialogs the same z-index.
=> docs: fix should not keep dialog always mounted

.changeset/wise-schools-complain.md, src/lib/internal/actions/interact-outside/action.ts
closes https://github.com/melt-ui/melt-ui/issues/1115
This closes an issue where clicking outside a dialog on a touch device would trigger a click event on the element underneath the dialog.
This only happens when using pointer events on touch devices. After `pointerup` is called on touch devices, we need to wait for a `click` event before triggering an outside interaction. There is a delay between `pointerup` and `click` during which we used to close the dialog and hence trigger a click event on the element under the dialog.
Technically this issue should also occur when using touch events, which we use when pointer events are not available, however this issue doesn't occur in our case when using touch events because we call `e.preventDefault()` which will prevent a click event occurring …
=> Fix(interact outside) touch devices leak click events to dom elements

src/lib/builders/listbox/create.ts
Listbox Refactor:
- setting `activeTrigger` in trigger action instead of in `openMenu` and in `safeOnMount` and in `effect([open])`
- using early return in `effect([open])` for cleaner code
=> refactor listbox

.changeset/dry-dolls-greet.md, src/lib/builders/link-preview/create.ts
closes https://github.com/melt-ui/melt-ui/issues/1060
setting `activeTrigger` in trigger action (when trigger is mounted) instead of in `safeOnMount`. This makes sure that we always have a reference to the up-to-date trigger every time a new trigger mounts. Currently, if you just unmount the trigger and remount it, we have a stale `activeTrigger` which breaks the behavior of the component as seen in the mentioned issue above
https://github.com/melt-ui/melt-ui/assets/53095479/c2dbc10c-314b-44a7-b91e-7330d74d66e5
https://github.com/melt-ui/melt-ui/assets/53095479/2d571348-4695-4307-9735-927e17c3d923
=> [link preview] fix content showing up at top left after remounting trigger

src/tests/dialog/Dialog.spec.ts
Currently in our dialog tests, every test repeats the assertions for opening a dialog so I refactored it into an `open` function.
Also most tests need `getByTestId('content')` and `getByTestId('overlay')`, so I added them to the object returned from `setup`
=> chore: refactor dialog tests

src/tests/dialog/Dialog.spec.ts
somehow forgot to remove a couple of unused variables in the dialog tests from PR https://github.com/melt-ui/melt-ui/pull/1127
=> chore: remove unused variables in tests

.changeset/old-taxis-yell.md, src/lib/builders/link-preview/create.ts
reset activeTrigger on trigger unmount. Currently, if you unmount the trigger, the content stays open because we never reset the `activeTrigger`. So on trigger destroy, we set `activeTrigger` to `null`
https://github.com/melt-ui/melt-ui/assets/53095479/edacd63f-160a-4241-9ef5-c0a1b48507b2
https://github.com/melt-ui/melt-ui/assets/53095479/767ac36f-988b-4483-9041-7f4348b7f689
=> fix(link-preview): reset activeTrigger on trigger unmount

.changeset/six-insects-joke.md, src/lib/builders/dialog/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/popover/create.ts, src/lib/internal/helpers/store/effect.ts, src/lib/internal/helpers/tests/effect.spec.ts, src/tests/dialog/Dialog.spec.ts, src/tests/dialog/DialogTest.svelte, src/tests/popover/Popover.spec.ts, src/tests/popover/PopoverTest.svelte
closes https://github.com/melt-ui/melt-ui/issues/1109
We now restore focus to the trigger (or using the `closeFocus` prop) in an `effect` that runs when `open` is `false`. In order to not focus the trigger on initial mount when `open` is `false`, I added a parameter `skipFirstRun` to the `effect` function that optionally skips the first run of the effect.
I also added regression tests for the dialog and popover. 
Also, in the menu builder, we are already doing what I implemented with the dialog and popover, which removes the need in the menu builder to manually focus the trigger in multiple places. And I cleaned up the effect in the menu component. 
https://github.com/melt-ui/melt-ui/assets/53095479/584dd6ad-bd39-4901-9ff1-2a0e987f1a2e …
=> fix(dialog,popover): restore focus when `open` set to `false`

.changeset/young-peaches-retire.md, src/docs/previews/dialog/main/tailwind/index.svelte, src/lib/internal/actions/interact-outside/action.ts, src/lib/internal/actions/interact-outside/types.ts, src/lib/internal/actions/modal/action.ts, src/lib/internal/helpers/debounce.ts, src/tests/dialog/Dialog.spec.ts, src/tests/dialog/DialogTest.svelte, src/tests/utils.ts
Closes https://github.com/melt-ui/melt-ui/issues/917, https://github.com/melt-ui/melt-ui/issues/1128
This PR adds the ability for a DOM element to intercept an outside interaction by calling `e.stopPropagation()`.
Let's use an example that demonstrates how the DOM behaves and the challenges it imposes for this PR:
On a mouse device, clicking an element will trigger all of the following events:
1. pointerdown
2. pointerup
3. mousedown
4. mouseup
5. click
If the user intercepts the `pointerdown` event, `pointerup` and `click` will still trigger while the mouse events will not.
If the user intercepts `mousedown` or `mouseup`, all the other events will still be triggered.
Let's use another example: on a touch device, clicking an element will trigger all of the following events:
1. pointerdown …
=> Fix(interact outside): enable interact outside interception

src/tests/dialog/Dialog.spec.ts
This PR improves the changes introduced by https://github.com/melt-ui/melt-ui/pull/1118
Currently in touch devices, we wait for a `click` event after a `pointerdown` and a `pointerup` to prevent the events leaking to elements underneath the dialog.
So now, instead of listening to `pointerup`, `touchend`, `mouseup`, we can just listen to the `click` event.
=> chore: fix dialog test name

src/tests/popover/Popover.spec.ts
Currently in our popover tests, every test repeats the assertions for opening a popover so I refactored it into an `open` function.
=> chore: refactor popover tests

.changeset/good-pants-crash.md, src/lib/builders/dialog/create.ts, src/lib/builders/popover/create.ts, src/lib/internal/actions/focus-trap/action.ts, src/tests/dialog/Dialog.spec.ts, src/tests/popover/Popover.spec.ts, src/tests/popover/PopoverTest.svelte
closes https://github.com/melt-ui/melt-ui/issues/1134
We should not let the focus trap package deactivate the focus trap on an outside interaction because they use capture events which will fire even if an element intercepted the event. Therefore we should never let the focus trap package deactivate based on an outside interaction but rather when the dialog or popover unmount which is already implemented in the destroy method of the focus trap action.
https://github.com/melt-ui/melt-ui/assets/53095479/3445b6eb-df44-4569-9ccc-a08d733b3fb6
https://github.com/melt-ui/melt-ui/assets/53095479/6cb1fe7d-019c-4fde-b7c8-d71befb704ac
=> Fix(focus trap): trap deactivation intercepted interact outside

.changeset/hungry-steaks-whisper.md, src/lib/builders/dialog/create.ts, src/lib/builders/popover/create.ts, src/lib/internal/actions/focus-trap/action.ts, src/lib/internal/actions/popper/action.ts, src/tests/dialog/Dialog.spec.ts, src/tests/dialog/DialogTest.svelte, src/tests/popover/Popover.spec.ts, src/tests/popover/PopoverTest.svelte, src/tests/utils.ts
closes https://github.com/melt-ui/melt-ui/issues/1132
We should not let the focus trap package deactivate the focus trap on an escape key press because they use capture events which will fire even if an element intercepted the event. Therefore we should never let the focus trap package deactivate based on an escape key press but rather when the dialog or popover unmount which is already implemented in the destroy method of the focus trap action.
https://github.com/melt-ui/melt-ui/assets/53095479/5dccb797-25fb-420b-afd6-13ad5272fac2
https://github.com/melt-ui/melt-ui/assets/53095479/9520d91e-7ff2-46b5-af8b-f5532460261e
=> fix(focus trap): focus trap deactivates on intercepted escape

.changeset/tough-squids-rescue.md, src/lib/builders/context-menu/create.ts, src/lib/builders/date-range-field/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/internal/actions/focus-trap/action.ts, src/lib/internal/actions/focus-trap/types.ts, src/lib/internal/actions/interact-outside/action.ts, src/lib/internal/actions/interact-outside/types.ts, src/lib/internal/actions/modal/action.ts, src/lib/internal/actions/modal/types.ts, src/lib/internal/actions/popper/action.ts, src/tests/combobox/Combobox.spec.ts, src/tests/context-menu/ContextMenu.spec.ts, src/tests/dialog/Dialog.spec.ts, src/tests/dialog/DialogNested.spec.ts, src/tests/dialog/DialogTransitions.spec.ts, src/tests/popover/Popover.spec.ts, src/tests/portal/Portal.spec.ts, src/tests/tooltip/Tooltip.spec.ts
This PR should be merged after https://github.com/melt-ui/melt-ui/pull/1135 and https://github.com/melt-ui/melt-ui/pull/1133
We currently set the same options for the focus trap action in multiple places (popover, dialog, popper). This PR moves all the same options that we use to be the default ones used in `createFocusTrap()` to avoid redundancy. Also as new issues come up with the focus trap (like the ones that are solved in the prerequisite PRs), there is the possibility of missing all the different places that use the focus trap that should behave the same way.
I also cleaned up `createFocusTrap()` and made it more similar to how our other actions behave.
And I cleaned up the dialog content builder.
=> refactor: focus-trap

src/docs/components/custom-event-dialog.svelte, src/docs/components/tables/custom-events-table.svelte, src/docs/components/tables/data-attr-table.svelte, src/docs/components/tables/props-table.svelte, src/docs/components/tables/returned-props-table.svelte, src/docs/components/type-dialog.svelte, src/docs/previews/dialog/alert/tailwind/index.svelte, src/docs/previews/dialog/controlled/tailwind/index.svelte, src/docs/previews/dialog/main/tailwind/index.svelte, src/docs/previews/dialog/nested/tailwind/index.svelte, src/routes/+page.svelte, src/stories/Dialog/BaseDialog.svelte
replaced a bunch of arbitrary tailwind classes with built-in tailwind classes.
- `top-[50%]` -> `top-1/2`
- `translate-x-[-50%]` -> `-translate-x-1/2`
- etc.
=> docs: improve tailwind classes

src/tests/combobox/Combobox.spec.ts, src/tests/combobox/ComboboxTest.svelte
add regression tests to prevent issue reported in https://github.com/melt-ui/melt-ui/pull/1038#issuecomment-2016526702 
when combobox is open and clicking outside on a different input, the combobox closes as expected, however the click on the input is prevented and the it does not get focused. You should be able to click onto an input while the combobox is open and have the input be focused after the combobox closes.
=> test(combobox): add interact outside tests

src/lib/internal/helpers/id.ts
add a missing import for the `Expand` type.
=> chore: fix missing `Expand` type import

.changeset/cyan-toes-jam.md, src/lib/builders/context-menu/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/helpers/store/effect.ts, src/lib/internal/helpers/tests/effect.spec.ts
This PR adds a new prop `runAfterTick` to `effect`.
Previously we needed to run `tick()` in many builders to prevent https://github.com/melt-ui/melt-ui/issues/1048 where the DOM hasn't updated yet before our effect ran which caused issues, however after adding a tick to solve that issue, we then ran into a new issue https://github.com/melt-ui/melt-ui/pull/1087 where we were getting memory leaks due to not calling the cleanup functions both before and after the `tick`. So by adding the `runAfterTick` prop, our effect will run after the DOM has updated and it removes the need to make sure we call all the cleanup functions twice in so many builders.
=> refactor(internal): add `runAfterTick` prop to `effect`

.changeset/new-hairs-vanish.md, src/docs/content/builders/slider.md, src/docs/data/builders/slider.ts, src/docs/previews/slider/multiple/tailwind/index.svelte, src/docs/previews/slider/multiple/tailwind/slider.svelte, src/lib/builders/slider/create.ts, src/lib/builders/slider/types.ts
Closes #1122.
I added a `disableSwap` option to sliders which disables the automatic ordering of the value array. Therefore it's now possible to have arrays like these: `[25, 20, 30]`, whereas before the value arrays were always automatically sorted. This is important because in some instances users might want indexes to hold specific meaning, so if the values get swapped around there's no way of keeping track of the individual values.
I also added an example for it, which demonstrates the different behaviors:
=> Feat: add `autoSort` option for sliders

src/docs/data/builders/combobox.ts
In the docs for combobox it mentions 'item' in the API Reference area. It seems that it changed to 'option' at some point but was forgotten to be updated in the docs accordingly. This changes 'item' to 'option'.
=> docs(combobox): change item to option

.changeset/moody-jokes-peel.md, src/lib/builders/tooltip/create.ts
closes https://github.com/melt-ui/melt-ui/issues/886
The reason issue https://github.com/melt-ui/melt-ui/issues/886 occurs is because `clientX` is smaller by 1 than `triggerRect.left`, which causes us to inaccurately "think" that the pointer is outside the trigger which causes the tooltip to close. This is due to sub-pixel rendering and rounding issues by the browser. 
To make sure this doesn't happen, we now keep track of 2 extra variables `isPointerInsideTrigger` and `isPointerInsideContent` that are set on `pointerenter` and `pointerleave` for the trigger and content respectively. And `isPointerInsideTrigger` and `isPointerInsideContent` are taken into account in addition to `pointInPolygon()` when deciding whether the pointer is inside the tooltip area. …
=> Fix: tooltip closes while pointer is still inside trigger

src/docs/content/builders/calendar.md
This pull request updates the documentation to include instructions for utilizing different calendar systems for complete localization in the Calendar builder. Users can now refer to the documentation to learn how to configure the Calendar builder to support various calendar systems, such as the Persian calendar, to meet their localization needs.
Merely using the locale prop does not change the calendar system; instead, it adjusts the weekdays and month names while retaining the Georgian calendar for the month display.
Changes:
-Extends the documentation to include detailed instructions on configuring different calendar systems for the calendar.
=> docs: completes documentation for localization using specific calendar system for the calendar. 

src/docs/content/controlled.md
Remove an unused `import` in the docs
This also closes https://github.com/melt-ui/melt-ui/issues/1097
=> docs: Remove unused `import` code in the document

.changeset/old-bees-breathe.md, src/lib/builders/listbox/create.ts
The listbox builder is used by the Select & the Combobox builder. This also closes #1193
=> fix: add `data-state` to Listbox builder

.changeset/tasty-tools-accept.md, src/docs/data/builders/combobox.ts, src/docs/data/builders/radio-group.ts, src/lib/builders/radio-group/create.ts, src/lib/builders/radio-group/types.ts, src/tests/radio-group/RadioGroup.spec.ts, src/tests/radio-group/RadioGroupTest.svelte
hidden input element on radio group builder always had undefined `name` attribute
added a test and updated docs
=> feat(radio group): add `name` prop to radio group builder

package.json
After cloning the repository and installing the dependencies, it would be nice
if `svelte-kit sync` was executed automatically and preparing the repository
(basically adding all the types and tsconfig files).
=> chore: add `prepare` script

.changeset/curly-mails-jump.md, src/lib/internal/helpers/date/calendar.ts
Solves https://github.com/melt-ui/melt-ui/issues/1213.
This was solved by me in https://github.com/radix-vue/radix-vue/pull/1029 but @epr3 suggest you might also need this fix. 
Root cause: when 6th week will start in new month then `startFrom` will be `undefined`. Currently `if (!startFrom)` was using first day of next month, but then in creation of extraDaysArray all dates were incremented which resulted in first day of new month being missed.
I am not familliar with Svelte so I do not have any test case for this. But you might want to cross check with how it **might be** tested in radix-vue: https://github.com/radix-vue/radix-vue/pull/1029/files#diff-a067dd33cc3ddceb2d881b1d1984509071d713079564a97d9ea182084284e2f8
At least using August 2024 instead of January 1980 might help if you are …
=> fix(Calendar): sometimes first day of next month is missing

.changeset/rude-pugs-tease.md, src/docs/data/builders/table-of-contents.ts, src/lib/builders/table-of-contents/create.ts, src/lib/builders/table-of-contents/types.ts
TableOfContents interaction observer allows passing in scroll offset, which can be used to account for fixed/sticky headers when scrolling, but there is no way to cater for that in interaction observer.
This PR adds a rootMargin argument for TableOfContents builder, which is then passed to the InteractionObserver constructor, thus catering for viewport customisation and use cases like fixed headers/footers.
=> feat: add rootMargin to TableOfContents builder

src/routes/(landing-ui)/popover.svelte, src/routes/+layout.svelte, src/routes/docs/+layout.svelte
Skip to content button added. It does not work so well on the first page - it is the first item in the navigation order, but the focus is set to the popover button. Let me know what you think, and if there's something in the code that needs updating.
Resolves issue [#687](https://github.com/melt-ui/melt-ui/issues/687)
=> Resolves #687 Add skip to content button

.changeset/purple-eggs-flow.md, src/docs/data/builders/table-of-contents.ts, src/docs/previews/table-of-contents/main/tailwind/index.svelte, src/lib/builders/table-of-contents/create.ts, src/lib/builders/table-of-contents/types.ts
Hello! This is a first attempt to provide the pushState function from SvelteKit to the Table of Contents builder. Using history.pushState not only throws a warning but also breaks some of SvelteKit's $page store state. I'd love to hear your comments and explore other possible implementation approaches.
=> Feat: add a pushState function as parameter to the table of content builder

src/routes/(landing-ui)/search.svelte
fixes #1214 
Basically when a user presses Ctrl + K or clicks the search icon, the search input should pop up and the input field should be auto focused. Before this pr the `openFocus` of the search dialog ran before the input field was rendered which passed undefined to `createDialog()` and the focus remained at the default element rather than search input. This pr fix that autofocus issue.
=> fix: #1214 Search input not auto focused on activation

src/routes/(landing-ui)/search.svelte
Search Results had lower z-index than the overlay.
=> Search results clickable now on melt docs.

.changeset/flat-books-jam.md, src/docs/data/builders/slider.ts, src/lib/builders/slider/create.ts
It is sometimes desirable to customize the behaviour of the slider based on whether it is active / being interacted with.
For example, I have a slider that snaps to certain predefined values when the user drags the slider, but can be set with a text input to non-snapped values on my project.
Due to `steps`, the slider calls `value.update` whenever `$value` changes, even if the change comes from an external interaction. To prevent this, I've patched `@melt-ui/svelte` to expose the `isActive` store as `active`, enabling the following behaviour:
```ts
export let valueStore: Writable<number>;
const {
elements: { root, range, thumbs },
states: { active }
} = createSlider({
value: {
...derived(valueStore, ($value) => [$value]),
set(newValue: number[]) {
if (!$active) return; …
```
=> feat: expose active state on slider

.changeset/three-hounds-count.md, src/lib/internal/helpers/index.ts
Fixes #1293
By changing the order of imports (to order of usage), the runtime error disappears.
`callbacks.js` module is used inside of  `makeElement.js` module and therefore have to be imported before
=> fix webpack noop undefined runtime error by changing import order of helpers

package.json
Using `vitest 3`, I get this error when I run my tests: 
```
Error: Failed to resolve entry for package "@melt-ui/svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@melt-ui/svelte" package
```
Adding this default export is fixing the issue. _(I have it locally in my pnpm paches atm)_
=> Fix main/module/exports for "."
