melt-ui/melt-ui

src/lib/internal/helpers/builder.ts, src/lib/internal/helpers/style.ts, src/lib/internal/helpers/uuid.ts
Some of these might be too verbose for your liking, so no offense will be taken if you remove some bits!
=> chore: add comments to code

.changeset/slimy-laws-float.md, src/lib/builders/select/index.ts
=> fix: prevent focus on mousedown

.changeset/kind-tomatoes-cry.md, src/lib/builders/slider/index.ts
=> fix slider bug on mobile

.changeset/fast-wasps-burn.md, src/lib/builders/slider/index.ts
=> fix slider

.changeset/two-frogs-explain.md, src/app.d.ts, src/lib/builders/radio-group/index.ts, src/lib/builders/tabs/index.ts, src/lib/builders/toggle-group/index.ts, src/lib/internal/helpers/locale.ts, src/lib/internal/types.ts
This pull request introduces a new feature that enables the detection of the text direction in the browser and addresses any associated pending tasks.
=> feat: detect browser text direction

src/routes/docs/builders/popover/+page.svelte, src/routes/docs/builders/popover/code.ignore-svelte
=> docs: add code ignore to popover

src/routes/docs/builders/switch/(snippets)/controlled.ignore-svelte, src/routes/docs/builders/switch/(snippets)/disable.ignore-svelte, src/routes/docs/builders/switch/(snippets)/index.ts, src/routes/docs/builders/switch/+page.svelte
Updates documentation for [switch](https://www.melt-ui.com/docs/builders/switch), so it is up the same standard as other builders
=> Documentation for switch

src/routes/docs/builders/separator/(examples)/(preview)/css.ignore-svelte, src/routes/docs/builders/separator/(examples)/(preview)/index.ts
If this PR is alright I will continue porting the other components over to CSS as well.
Should I make a PR for every component separately or should I just make a single large PR for this?
=> feat: css example for separator

.changeset/chatty-walls-swim.md, src/lib/builders/tags-input/helpers.ts, src/lib/builders/tags-input/index.ts, src/routes/docs/builders/tags-input/(examples)/(preview)/preview.svelte, src/routes/docs/builders/tags-input/(examples)/(preview)/tailwind.ignore-svelte
Fixes #115 
Reworked all the action logic. 
Tags no longer have an action and it's all managed by the `root` and `input` actions
this will also make it easier to add features :)
=> Rework tags-input

src/app.postcss, src/routes/docs/+layout.svelte
The mobile styles need a decent refactor, but for the time being, this PR will fix some of the more obvious issues.
Closes: #123
=> [Docs]: Improve mobile styles

.changeset/nice-chairs-pull.md, src/lib/builders/select/index.ts
=> [Select] Add appropriate tab behavior

.changeset/forty-bags-decide.md, src/lib/builders/context-menu/index.ts, src/lib/builders/dropdown-menu/index.ts, src/lib/builders/menu/index.ts, src/lib/internal/helpers/rovingFocus.ts
=> [Dropdown/Context Menus] Update tab & scroll behaviors

.changeset/long-dots-wonder.md, src/lib/builders/toggle-group/index.ts, src/routes/docs/builders/toggle-group/(examples)/(preview)/preview.svelte
=> [Toggle Group] Refactor tab behavior

.changeset/stale-goats-know.md, src/lib/builders/toggle-group/index.ts
=> [Toggle Group]: focus selected first

src/routes/(components)/api.svelte, src/routes/(components)/h2.svelte, src/routes/(components)/h3.svelte, src/routes/(components)/p.svelte, src/routes/docs/builders/context-menu/+page.svelte, src/routes/docs/builders/dropdown-menu/+page.svelte, src/routes/docs/builders/label/+page.svelte
This PR cleans up the need for one off `<Docs.P>` styles to make things look good.
=> [Docs] cleanup one off styles

.changeset/chatty-lobsters-change.md, src/lib/builders/menu/create.ts
=> [Menus]: Close Menus on Tab press within submenus

.changeset/twenty-pans-mix.md, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/internal/helpers/typeahead.ts
=> [Menus] Fix submenu typeahead logic

.changeset/silly-vans-laugh.md, src/lib/builders/menu/create.ts, src/lib/internal/helpers/rovingFocus.ts
Closes: #127 
@pawelblaszczyk5 if you want to take a look at this one and make sure it closes your issue, that'd be appreciated!
=> [Dropdown Menu] Fix dropdown trigger tabindex issue

.changeset/mighty-goats-hear.md, .changeset/pretty-planes-smell.md, .changeset/rich-carpets-compete.md, src/lib/builders/combobox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/select/create.ts, src/lib/builders/slider/create.ts, src/lib/builders/tabs/create.ts
=> Several fixes

.changeset/six-starfishes-leave.md, src/lib/builders/menu/create.ts, src/lib/internal/helpers/rovingFocus.ts
=> [Menus] fix: dropdown submenu not closing

.changeset/dirty-weeks-turn.md, e2e/dropdown.spec.ts, playwright.config.ts, src/docs/previews/accordion/main/tailwind.svelte, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts
Closes: #199 
This PR updates the menu builders to function as expected on Firefox and other non-chromium browsers, as well as fixes lags introduced in a previous attempt at addressing the issue.
I'd love a second set of eyes/hands on the different menu components to ensure the behavior is expected.
=> [Menus] Fix menu lag & other issues

.changeset/friendly-brooms-own.md, src/docs/components/switch.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/radio-group/create.ts, src/lib/builders/tabs/create.ts, src/lib/internal/helpers/is.ts
=> [Multiple] Fix radio focus & other left click issues

.changeset/large-coins-breathe.md, src/lib/builders/combobox/create.ts
=> [Combobox] Fix menu open/close on tab

mdsvex.config.js, src/docs/components/markdown/a.svelte, src/docs/content/builders/dialog.md, src/docs/previews/dialog/alert/tailwind.svelte, src/docs/previews/dialog/drawer/tailwind.svelte, svelte.config.js
Adds some additional examples for components and usage in the dialog docs.
=> [Dialog] Doc updates

src/lib/builders/accordion/tests/Accordion.spec.ts, src/lib/builders/accordion/tests/AccordionTest.svelte
Hey!
I've just started learning Svelte and discovered this library, so there's a lot of catching up for me, but I really like how it already looks, and I'd love to be able to contribute to it.  
In the checklist in this issue: https://github.com/melt-ui/melt-ui/issues/148, I saw there are a bunch of tests still needed, so I gave it a shot and have written some for Accordion component. 
Once I get to know both Svelte and Melt-UI better, I hope to deliver more meaningful contributions.
=> [Accordion] Add tests

.changeset/five-badgers-rescue.md, .changeset/little-pumas-move.md, .changeset/selfish-mayflies-bake.md, src/docs/components/type-dialog.svelte, src/docs/content/builders/dialog.md, src/docs/content/builders/slider.md, src/docs/previews/context-menu/main/tailwind.svelte, src/docs/previews/dialog/drawer/tailwind.svelte, src/docs/previews/dialog/main/tailwind.svelte, src/docs/previews/dialog/nested/tailwind.svelte, src/docs/previews/dropdown-menu/main/tailwind.svelte, src/docs/previews/menubar/main/tailwind.svelte, src/docs/previews/slider/vertical/tailwind.svelte, src/lib/builders/slider/create.ts, src/lib/builders/tooltip/create.ts, src/stories/Collapsible/Collapsible.svelte, src/stories/Dialog/BaseDialog.svelte, src/stories/Dialog/Dialog.svelte, src/stories/Dialog/NestedDialog.svelte
=> Several improvements

src/docs/content/builders/dialog.md
=> [Docs] Cleanup dialog docs

src/docs/components/nav/mobile-nav.svelte
Would appreciate it if some Android and other iOS users could check this out, @geerew @TGlide. This fixes it for me but want to make sure it doesn't interfere with other devices.
Closes: #226
=> [Docs] Add safe area padding for mobile menu

.changeset/soft-rabbits-poke.md, src/lib/builders/hover-card/create.ts
=> [Hover Card] Fix bug where link is unclickable on mobile

.changeset/shaggy-snails-perform.md, src/docs/data/builders/context-menu.ts, src/docs/data/builders/dropdown-menu.ts, src/docs/data/builders/menu.ts, src/docs/data/builders/menubar.ts, src/docs/previews/context-menu/main/css/index.svelte, src/docs/previews/context-menu/main/tailwind/index.svelte, src/docs/previews/dropdown-menu/main/tailwind/index.svelte, src/docs/previews/menubar/main/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/menubar/types.ts
- Adds the `group` & `groupLabel` elements to the menu elements.
- Cleans up some of the menu docs
=> [Menu] Add `group` and `groupLabel` elements & update docs

.changeset/tricky-boats-breathe.md, src/docs/content/builders/tags-input.md, src/lib/builders/tags-input/create.ts, src/lib/builders/tags-input/types.ts, src/lib/index.ts, src/tests/tags-input/TagsInput.spec.ts, src/tests/tags-input/TagsInput.svelte
Closes #348 
I've also added some tests for the tags
=> fix: tag being created/updated even if not valid

.changeset/plenty-hotels-glow.md, src/lib/builders/select/create.ts, src/tests/select/Select.spec.ts
=> Resolve multi-select bug

.changeset/tall-crabs-marry.md, src/docs/previews/context-menu/main/css/index.svelte, src/docs/previews/context-menu/main/tailwind/index.svelte, src/docs/previews/dropdown-menu/main/tailwind/index.svelte, src/docs/previews/menubar/main/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts, src/lib/builders/menubar/create.ts, src/lib/builders/select/create.ts, src/tests/select/Select.spec.ts
=> [Menubar] Improve performance / Fix Lag

.changeset/great-pots-thank.md, src/lib/builders/context-menu/create.ts, src/lib/builders/menu/create.ts
=> [Context Menu] Fix inability to submit forms

src/lib/builders/context-menu/create.ts
=> fix: context menu not closing when clicking on svg element

README.md
users can add to this list by sending a PR to https://github.com/svelte-society/sveltesociety.dev/ as described on https://sveltesociety.dev/help/submitting?type=component
=> docs: more exhaustive list of component libraries

src/docs/previews/accordion/disabled/tailwind/index.svelte, src/docs/previews/accordion/multiple/tailwind/index.svelte, src/docs/previews/pagination/main/tailwind/index.svelte, src/docs/previews/toggle-group/main/tailwind/index.svelte, src/docs/previews/toggle/main/tailwind/index.svelte
Updates some of the example styles to align with the new styles demonstrated throughout the docs.
=> update example styles

.changeset/lovely-years-laugh.md, src/docs/data/builders/tags-input.ts, src/lib/builders/tags-input/create.ts
=> Add isInputValid, addTag, etc to inputTags

.storybook/main.ts
`lint` is failing on the main branch and it's unrelated to this PR
=> chore: remove unused imports

.changeset/lucky-mirrors-count.md, src/lib/builders/dropdown-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menu/types.ts
I've attempted to create a fix for this issue #https://github.com/melt-ui/melt-ui/issues/466 that I created. looking forward to hear thoughts / feedback
=> Add option to control typeahead

.changeset/silver-shoes-fry.md, src/lib/builders/combobox/create.ts, src/lib/builders/select/create.ts, src/lib/internal/helpers/ignore.ts, src/lib/internal/helpers/index.ts, src/lib/internal/helpers/is.ts
=> improve: handling of custom label/ids for select & combo

package.json, pnpm-lock.yaml, src/routes/+layout.svelte
Just need to add those two env vars to Vercel and this will be good to go :)
=> Add Fathom analytics

src/docs/content/installation.md
=> Docs: Added missing export

.changeset/light-flies-pretend.md, src/docs/data/builders/tooltip.ts, src/lib/builders/select/create.ts, src/lib/builders/tooltip/create.ts, src/lib/builders/tree/create.ts
Runs prettier and fixes one eslint issue.
=> Resolve linter issues preventing PR checks from passing

.changeset/swift-seas-exercise.md, src/lib/builders/combobox/create.ts
=> Fix submit form on Enter

src/docs/content/builders/label.md
=> fix: update `usage` code section for label builder

src/docs/content/transitions.md
=> Update transitions.md - fixed minor typo

.changeset/silver-mails-draw.md, src/lib/builders/pin-input/create.ts
=> fix: bind `$valueStr` store to `hiddenInput` of `pin-input` builder

.changeset/unlucky-cobras-vanish.md, src/docs/data/builders/pin-input.ts, src/lib/builders/pin-input/create.ts, src/lib/builders/pin-input/types.ts
I'm only wondering if default values are set than the mask is immediately shown. Then again I don't think it's logical to use default values and mask together?
Fixes #493
=> feat: pin input mask option

.changeset/fuzzy-jars-tie.md, src/lib/builders/combobox/create.ts
=> Removed manual focus regain code + changset

.changeset/hungry-queens-hide.md, src/lib/builders/accordion/create.ts, src/lib/builders/combobox/create.ts, src/lib/builders/context-menu/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/pin-input/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/select/create.ts, src/lib/builders/slider/create.ts, src/lib/builders/tags-input/create.ts, src/lib/builders/tooltip/create.ts, src/lib/builders/tree/create.ts
=> chore: return ids from builders

src/docs/data/builders/select.ts
- Issue: https://github.com/melt-ui/melt-ui/issues/604 (Issue available, Not assigned) 
- Typo in the ```select``` docs 
<br>
<br>
- Change ```onSelectChange``` to ```OnSelectedChange```
<br>
<br>
- **select.ts** (src/docs/data/builders/select.ts)
<br>
=> fix: Corrected select builder docs

src/docs/content/transitions.md
=> docs: corrected line highlight

src/docs/previews/toggle-group/main/css/index.svelte, src/docs/previews/toggle/main/css/index.svelte
Part of https://github.com/melt-ui/melt-ui/issues/574
=> docs: add css example for Toggle Group

other/globalcss.html, other/tailwindconfig.html, src/docs/components/code-block.svelte, src/docs/components/file-tabs/index.ts, src/docs/components/file-tabs/list.svelte, src/docs/components/file-tabs/root.svelte, src/docs/components/file-tabs/tab.svelte, src/docs/components/file-tabs/tabs.svelte, src/docs/components/preview-wrapper.svelte, src/docs/components/preview.svelte, src/docs/highlighter.ts, src/markdown.postcss
Makes the file tabs that come along with the component previews feel more connected and provides a familiar IDE tab experience.
=> Refresh component preview file tabs

src/docs/previews/dropdown-menu/main/css/index.svelte, src/docs/previews/dropdown-menu/main/tailwind/index.svelte, src/docs/previews/link-preview/main/css/index.svelte, src/docs/previews/menubar/main/css/index.svelte, src/docs/previews/progress/main/css/index.svelte
Hi, I finished the previews for
- Dropdown menu
- Link preview
- Menubar
- Progress
While writing the CSS, I realized that the `ring` utility was challenging for me. Usually in my projects, I use an `outline` but with **Tailwind** they use `box-shadow` (my kryptonite 😵‍💫).
I also ran into an issue with the `focus-visible` (in the Dropdown menu preview). For some reason the styles were not applied when the element is focused.
=> [Doc] CSS Previews for Dropdown menu, Link preview, Menubar and Progress

src/docs/data/builders/table-of-contents.ts, src/lib/builders/table-of-contents/create.ts, src/lib/builders/table-of-contents/events.ts
Based on Hugo's comments on discord
=> Docs: Update ToC API documentation

src/docs/previews/switch/main/css/index.svelte
Added CSS example for switch component
=> Docs: add CSS example for switch component

.changeset/eleven-geese-hope.md, .eslintrc.cjs, src/docs/data/builders/table-of-contents.ts, src/docs/previews/context-menu/main/tailwind/index.svelte, src/docs/previews/dropdown-menu/main/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/table-of-contents/events.ts, src/tests/dropdown-menu/DropdownMenu.spec.ts, src/tests/dropdown-menu/DropdownMenuForceVisibleTest.svelte, src/tests/dropdown-menu/DropdownMenuTest.svelte
=> fix: loop prop in menus

.eslintrc.cjs, src/tests/label/Label.spec.ts, src/tests/label/LabelTest.svelte
=> Add label test

.changeset/afraid-peaches-eat.md, src/lib/builders/context-menu/create.ts
=> fix context menu trigger bug

src/docs/previews/popover/main/css/index.svelte, src/docs/previews/popover/nested/css/index.svelte
#574  CSS preview for Popover > Main component
=> Docs: CSS preview for popover component

.changeset/nasty-suits-sit.md, src/docs/previews/context-menu/main/tailwind/index.svelte, src/lib/builders/context-menu/create.ts, src/lib/builders/menu/create.ts, src/tests/context-menu/ContextMenu.spec.ts, src/tests/context-menu/ContextMenuTest.svelte
Closes: #703
-- 
Context menu IDs weren't updated to the BYOID.
=> fix: context menu id issues

.changeset/twenty-lemons-sneeze.md, src/lib/builders/menubar/create.ts, src/lib/builders/slider/create.ts, src/lib/builders/slider/types.ts, src/tests/collapsible/Collapsible.spec.ts, src/tests/collapsible/CollapsibleTest.svelte, src/tests/context-menu/ContextMenu.spec.ts, src/tests/dialog/DialogTest.svelte
Also adds a few more tests to keep chipping away at them 🫡
=> Fix: Menubar Menu BYOID Issues

vite.config.ts
Tests are retried 3 times if they fail to cover flaky cases.
=> chore: Added retries for tests

.changeset/tricky-readers-bow.md, src/lib/builders/listbox/create.ts, src/tests/select/Select.spec.ts, src/tests/select/SelectTest.svelte
=> fix: Select - toggle when elements within trigger are clicked

src/docs/content/builders/dialog.md
=> fix (docs): small error in dialog docs

.changeset/clever-bananas-cheer.md, src/lib/builders/popover/create.ts, src/tests/popover/Popover.spec.ts
Closes: #763 
Test case added as well.
=> fix: popover trigger toggle

.changeset/serious-fireants-tickle.md, src/lib/internal/helpers/attr.ts
=> fix: `aria-disabled` attr types

.changeset/cool-wolves-brush.md, src/lib/builders/dialog/create.ts
=> fix: remove aria controls from dialog

.changeset/late-donuts-care.md, src/docs/previews/accordion/main/tailwind/index.svelte, src/lib/builders/listbox/create.ts, src/lib/internal/helpers/is.ts, src/lib/internal/helpers/object.ts, src/tests/combobox/Combobox.spec.ts, src/tests/combobox/ComboboxTest.svelte
=> Remove undefined properties before deepEquals

.changeset/witty-cobras-type.md, src/lib/builders/listbox/create.ts
=> fix: Listbox `removeScroll` bug

.changeset/calm-zebras-hug.md, src/lib/internal/helpers/typeahead.ts
=> fix: Listbox - ignore certain typeahead keys

.changeset/cuddly-terms-love.md, src/lib/builders/pin-input/create.ts, src/tests/pin-input/PinInput.spec.ts, src/tests/pin-input/PinInputTest.svelte
I think this is what is causing my test to fail in:
https://github.com/huntabyte/bits-ui/pull/227
edit: yep, seems like this works!
also added tests to test this and test other PIN Inputs features
=> fix: PIN Input - fix `delete` key event handling and add tests

src/docs/content/builders/date-picker.md
=> docs: fix typo on Date Picker page

.changeset/gorgeous-worms-pretend.md, src/lib/builders/calendar/create.ts, src/lib/builders/date-field/create.ts, src/lib/builders/range-calendar/create.ts
=> fix: datepicker types

.changeset/big-walls-yell.md, src/lib/builders/radio-group/create.ts, src/tests/radio-group/RadioGroup.spec.ts, src/tests/radio-group/RadioGroupTest.svelte
=> fix: disabled radio group keyboard navigation

package.json, pnpm-lock.yaml
- upgrade clsx from 1.2.1 to 2.1.0
v2 changes are listed on https://github.com/lukeed/clsx/releases/tag/v2.0.0
=> chore: upgrade clsx to v2

.changeset/plenty-doors-rest.md, src/docs/content/builders/combobox.md, src/docs/content/builders/select.md, src/docs/data/builders/combobox.ts, src/docs/previews/combobox/group/tailwind/index.svelte, src/lib/builders/listbox/create.ts, src/lib/builders/select/create.ts
Closes: #831 
creates group and group label in listbox for both select and combobox builders. Also adds some missing entries in the select and combobox api reference
=> Combobox: add group and groupLabel elements

.changeset/nice-stingrays-sell.md, src/lib/builders/listbox/create.ts, src/tests/select/Select.spec.ts
=> fix: add type="button" to listbox trigger

src/docs/data/builders/select.ts, src/docs/data/builders/tags-input.ts, src/docs/previews/calendar/main/tailwind/LocaleCombobox.svelte, src/docs/previews/date-field/main/tailwind/LocaleCombobox.svelte, src/docs/previews/date-picker/main/tailwind/LocaleCombobox.svelte, src/docs/previews/date-range-field/main/tailwind/LocaleCombobox.svelte, src/docs/previews/date-range-picker/main/tailwind/LocaleCombobox.svelte, src/docs/previews/range-calendar/main/tailwind/LocaleCombobox.svelte
=> Docs fixes

.changeset/early-turtles-pay.md, src/lib/builders/date-picker/create.ts, src/lib/builders/date-range-picker/create.ts, src/tests/date-picker/DatePicker.spec.ts
=> fix: disabled date picker triggers

.changeset/popular-dolls-attend.md, src/lib/builders/toggle-group/create.ts, src/tests/toggle-group/ToggleGroup.spec.ts, src/tests/toggle-group/ToggleGroupTest.svelte
Closes: #810
Additional tests were added to support this as well.
=> fix: toggle group focus issues

.changeset/empty-peas-smoke.md, src/lib/builders/context-menu/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/helpers/attr.ts, src/lib/internal/helpers/elements.ts
I'm not sure how an issue hasn't been created for this yet, but we were handling nested portals incorrectly and doing some unnecessary searching when a custom prop was provided.
=> fix: portal issues

.changeset/happy-cheetahs-appear.md, src/lib/builders/calendar/create.ts, src/lib/builders/range-calendar/create.ts
=> fix(Calendar/Range Calendar): use `'button'` for button elements' `type`

src/docs/content/builders/tree.md, src/docs/data/builders/tree.ts, src/lib/builders/tree/events.ts, src/lib/builders/tree/types.ts
=> Fix: TreeView Docs

.changeset/angry-lobsters-relate.md, src/lib/builders/listbox/create.ts, src/tests/combobox/Combobox.spec.ts, src/tests/combobox/ComboboxForceVisibleTest.svelte
Closes: #1014 
Also adds additional tests for combobox.
=> fix: listbox programatic opening

.changeset/curly-olives-trade.md, src/lib/builders/date-range-field/create.ts, src/lib/builders/range-calendar/create.ts
=> fix: Range Calendar/Picker single day range selection

.changeset/ninety-oranges-collect.md, src/lib/builders/calendar/create.ts, src/tests/calendar/Calendar.spec.ts, src/tests/calendar/CalendarTest.svelte
=> fix: months not updating when changing options

.changeset/spotty-buttons-taste.md, src/lib/builders/range-calendar/create.ts, src/tests/range-calendar/RangeCalendar.spec.ts, src/tests/range-calendar/RangeCalendarTest.svelte
As suggested in #1070 fixing this also for range calendar (didn't realized it was not the same sorry)
=> fix: months not updating when changing options (range calendar)

src/lib/builders/context-menu/create.ts, src/lib/builders/dialog/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/actions/escape-keydown/action.ts, src/lib/internal/actions/focus-trap/action.ts, src/lib/internal/actions/interact-outside/action.ts, src/lib/internal/actions/modal/action.ts, src/lib/internal/actions/popper/action.ts, src/lib/internal/actions/portal.ts
Use function inference for actions with the `satisfies` keyword to reduce unnecessary conditions while still ensuring type safety of parameters and function return type.
=> chore: improve action type inference

.github/workflows/ci.yaml, e2e/dialog.spec.ts, e2e/dropdown.spec.ts, e2e/utils.ts, playwright.config.ts
add regression test for https://github.com/melt-ui/melt-ui/pull/1118
=> test: dialog touch events when overlay is clicked

src/docs/data/builders/accordion.ts
=> docs: remove duplicate accordion props

src/docs/data/builders/accordion.ts, src/docs/data/builders/menu.ts, src/docs/data/builders/menubar.ts
=> docs: Remove invalid props from menu docs

src/lib/builders/context-menu/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/helpers/index.ts, src/lib/internal/helpers/pointer.ts
We currently have duplicate code in the tooltip and menu builders for checking if a pointer is inside a polygon of points. This PR aims to refactor this.
=> chore: refactor isPointerInGraceArea

.changeset/cyan-toes-jam.md, src/lib/builders/context-menu/create.ts, src/lib/builders/link-preview/create.ts, src/lib/builders/listbox/create.ts, src/lib/builders/menu/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/popover/create.ts, src/lib/builders/tooltip/create.ts, src/lib/internal/helpers/store/effect.ts, src/lib/internal/helpers/tests/effect.spec.ts
=> Revert "refactor(internal): add `runAfterTick` prop to `effect`"

.changeset/beige-actors-provide.md, src/lib/builders/date-field/create.ts, src/lib/builders/menubar/create.ts, src/lib/builders/scroll-area/create.ts
=> fix: type narrowing on more element builders

CONTRIBUTING.md
I think it was forgotten to change OctoBot in the text to Melt UI. 🙂
=> chore: Update CONTRIBUTING.md - OctoBot -> Melt UI

.changeset/old-parrots-scream.md, src/docs/data/long-types/floating-config.ts, src/lib/internal/actions/floating/action.ts, src/lib/internal/actions/floating/types.ts, src/lib/internal/types.ts
Currently when using builders like `createDropdownMenu`, `positioning.flip` is a boolean property. Meaning flipping of the menu in case of overflow can either be turned on or off.
**With `flip: false`:**
https://github.com/melt-ui/melt-ui/assets/9678787/33425aae-505b-4204-9b0a-df110dfb7a30
**With `flip: true`:**
https://github.com/melt-ui/melt-ui/assets/9678787/692c567d-96d5-41cb-b04a-839d3ef8e109
Notice how with `flip: true`  the menu is flipped on both axes in case of overflow.
It would be great if it was possible to customize the flip behaviour further than just turning it on or off.
This PR extends the flip options to optionally take an object with [flip customization options offered by Floating UI](https://floating-ui.com/docs/flip#options). This allows more fine-grained control over …
=> feat: allow passing Floating UI's `FlipOptions` to `positioning.flip` property 

.changeset/clean-tomatoes-lie.md, src/docs/data/builders/toast.ts, src/docs/previews/toast/progress/tailwind/index.svelte, src/docs/previews/toast/progress/tailwind/select-hover.svelte, src/lib/builders/toast/create.ts, src/lib/builders/toast/types.ts
Clean up version of #998 with [suggested changes](https://github.com/melt-ui/melt-ui/pull/998#issuecomment-1975127460).
=> Added prop to createToaster() to pause all timers on hover

.changeset/khaki-maps-relate.md, src/docs/previews/tags-input/main/tailwind/index.svelte, src/lib/builders/tags-input/create.ts
=> feat(tags-input): split on paste
